/**
 * Complete Curriculum Dataset (Levels 0 to 12)
 *
 * Fully structured pedagogical curriculum for Bengali Typing:
 * Concept → Demonstration → Guided Practice → Isolated Drill → Pattern Drill → Word Drill → Mixed Drill → Mastery Test
 */

import type { CurriculumLevel, CurriculumLesson } from './types';

export const CURRICULUM_LEVELS: CurriculumLevel[] = [
  // ── LEVEL 0: ORIENTATION & HOME ROW ──────────────────────────────
  {
    level: 0,
    title: 'পরিচিতি ও হোম রো (Orientation & Home Row)',
    tagline: 'টাইপিং শেখার সঠিক নিয়ম ও Home Row কি পরিচিতি',
    description: 'হাতের সঠিক পজিশন, কীবোর্ড লেআউট এবং হোম রো-এর ৮টি কি ধাপে ধাপে শিখুন।',
    badge: '🚀',
    modules: [
      {
        id: 'mod-0-1',
        level: 0,
        title: 'কীবোর্ড ও টাইপিং নিয়মাবলী',
        description: 'হাতের সঠিক অবস্থান ও বেসিক কনট্রোল কি',
        lessons: [
          {
            id: 'lesson-0-1',
            title: 'HR-01: প্রথম হাতের অক্ষর (া স ড ফ)',
            subtitle: 'Home Row বাম হাতের ৪টি কি',
            level: 0,
            moduleId: 'mod-0-1',
            moduleTitle: 'কীবোর্ড ও টাইপিং নিয়মাবলী',
            description: 'বাম হাতের আঙুল A, S, D, F কি-তে রেখে া, স, ড, ফ অক্ষরগুলো টাইপ করা শিখুন।',
            skills: ['home-left', 'space'],
            prerequisites: [],
            estimatedMinutes: 3,
            difficulty: 1,
            sections: [
              {
                id: 'sec-0-1-1',
                type: 'explanation',
                title: 'বাম হাতের পজিশন',
                instruction: 'বাম হাতের কনিষ্ঠা A (া), অনামিকা S (স), মধ্যমা D (ড), তর্জনী F (ফ) কি-তে রাখুন।',
                explanationText: 'টাইপিং করার সময় কিবোর্ডের দিকে তাকাবেন না। প্রতিবার টাইপ করার পর আঙুলগুলো স্থানে স্থির রাখুন।',
              },
              {
                id: 'sec-0-1-2',
                type: 'guided',
                title: 'একক অক্ষর অনুশীলন',
                instruction: 'স্ক্রিনের অক্ষরগুলো দেখে সঠিক আঙুল দিয়ে চাপুন।',
                items: ['া', 'স', 'ড', 'ফ', 'া', 'স', 'া', 'ফ', 'স', 'ড', 'স', 'ফ'],
                requiredAccuracy: 90,
              },
              {
                id: 'sec-0-1-3',
                type: 'mastery',
                title: 'প্রথম ৪ কি দ্রুততা যাচাই',
                instruction: '৯৫% নির্ভুলতায় এই ধাপটি শেষ করুন।',
                items: ['ফ', 'ড', 'স', 'া', 'া', 'স', 'ড', 'ফ', 'স', 'া', 'ফ'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-0-2',
            title: 'HR-02: ডান হাতের অক্ষর (গ ্ জ ক ল)',
            subtitle: 'Home Row ডান হাতের কি',
            level: 0,
            moduleId: 'mod-0-1',
            moduleTitle: 'কীবোর্ড ও টাইপিং নিয়মাবলী',
            description: 'ডান হাতের আঙুল J, K, L, ; এবং G, H কি-এর মাধ্যমে গ, ্, জ, ক, ল শিখুন।',
            skills: ['home-right'],
            prerequisites: ['lesson-0-1'],
            estimatedMinutes: 3,
            difficulty: 1,
            sections: [
              {
                id: 'sec-0-2-1',
                type: 'explanation',
                title: 'ডান হাতের পজিশন',
                instruction: 'ডান হাতের তর্জনী J (জ) ও H (্) / G (গ), মধ্যমা K (ক), অনামিকা L (ল) কি-তে রাখুন।',
                explanationText: '্ (হসন্ত) এবং গ কি দুটি তর্জনী দিয়েই টাইপ করা হয়।',
              },
              {
                id: 'sec-0-2-2',
                type: 'guided',
                title: 'ডান হাতের অক্ষর অনুশীলন',
                instruction: 'নির্দেশিত কিগুলো সাবলীলভাবে টাইপ করুন।',
                items: ['গ', '্', 'জ', 'ক', 'ল', 'গ', 'জ', 'ক', 'ল', 'ক', 'ল', 'জ', 'গ'],
                requiredAccuracy: 90,
              },
            ],
          },
          {
            id: 'lesson-0-3',
            title: 'HR-03: দুই ও তিন অক্ষরের Combination',
            subtitle: 'Syllables & Combinations',
            level: 0,
            moduleId: 'mod-0-1',
            moduleTitle: 'কীবোর্ড ও টাইপিং নিয়মাবলী',
            description: 'হোম রো-এর বর্ণগুলো মিলিয়ে সহজ শব্দাংশ টাইপ করুন।',
            skills: ['home-combos'],
            prerequisites: ['lesson-0-2'],
            estimatedMinutes: 4,
            difficulty: 2,
            sections: [
              {
                id: 'sec-0-3-1',
                type: 'pattern',
                title: 'শব্দাংশ (Syllables)',
                instruction: 'দুই অক্ষরের সমন্বয়ে গঠিত শব্দাংশগুলো অনুশীলন করুন।',
                items: ['সা', 'দা', 'গা', 'জা', 'কা', 'লা', 'ফা', 'দগ', 'সক', 'লগ'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-0-3-2',
                type: 'word',
                title: 'হোম রো শব্দ অনুভব',
                instruction: 'তিন अक्षরের সমন্বয়ে গঠিত হোম রো শব্দ।',
                items: ['সাদা', 'গাদা', 'জালা', 'দাদা', 'ফালা', 'সাদা', 'দাদা', 'গাদা'],
                requiredAccuracy: 92,
              },
            ],
          },
          {
            id: 'lesson-0-4',
            title: 'HR-04: হোম রো শব্দ ও Mastery Test',
            subtitle: 'Home Row Word Drill & Certification',
            level: 0,
            moduleId: 'mod-0-1',
            moduleTitle: 'কীবোর্ড ও টাইপিং নিয়মাবলী',
            description: 'হোম রো-এর বাস্তব শব্দ অনুশীলনের মাধ্যমে হোম রো মাস্টার করুন।',
            skills: ['home-words', 'home-mastery'],
            prerequisites: ['lesson-0-3'],
            estimatedMinutes: 5,
            difficulty: 2,
            sections: [
              {
                id: 'sec-0-4-1',
                type: 'word',
                title: 'Tiered Words (সহজ থেকে মাঝারি শব্দ)',
                instruction: 'হোম রো-এর সম্পূর্ণ শব্দ তালিকা অনুশীলন করুন।',
                items: ['জল', 'ফল', 'গল', 'জগ', 'গজ', 'সাজ', 'ঢল', 'ঝল', 'হল', 'জালা', 'ফালা', 'গালা', 'ডালা', 'সাজা', 'ঢাল', 'গলা', 'ঝাল', 'সফল', 'ফসল', 'গজল', 'অলস'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-0-4-2',
                type: 'mastery',
                title: 'Home Row Mastery Test',
                instruction: '৯৫% নির্ভুলতায় এই টেস্টটি শেষ করে Level 1 আনলক করুন।',
                items: ['া', 'স', 'ড', 'ফ', 'গ', 'জ', 'ক', 'ল', 'সা', 'দা', 'গা', 'কা', 'লা', 'জল', 'ফল', 'গল', 'সাদা', 'গাদা', 'জালা', 'দাদা', 'ফালা', 'সফল', 'ফসল', 'জঙ্গল', 'জলসা', 'অলস', 'জগৎ'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 1: TOP ROW, BOTTOM ROW & ROW MIXING ─────────────────────
  {
    level: 1,
    title: 'টপ রো, বটম রো ও রো মিক্সিং (Rows & Transitions)',
    tagline: 'কীবোর্ডের সকল রো চিনে ফেলা এবং সমন্বিত টাইপিং',
    description: 'Top Row, Bottom Row এবং ৩টি রো একত্রে মিলিয়ে টাইপ করার দক্ষতা অর্জন করুন।',
    badge: '🌿',
    modules: [
      {
        id: 'mod-1-1',
        level: 1,
        title: 'টপ রো ও বটম রো পরিচিতি',
        description: 'উপরের ও নিচের সারির অক্ষর পরিচিতি',
        lessons: [
          {
            id: 'lesson-1-1',
            title: 'TR-01: টপ রো অক্ষর ও শব্দ',
            subtitle: 'Top Row Key Practice',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'টপ রো ও বটম রো পরিচিতি',
            description: 'টপ রো-এর ঙ, র, ট, ে, য, ু, ি, ো, প বর্ণগুলো এবং শব্দ অনুশীলন করুন।',
            skills: ['top-row-keys', 'top-row-words'],
            prerequisites: ['lesson-0-4'],
            estimatedMinutes: 4,
            difficulty: 2,
            sections: [
              {
                id: 'sec-1-1-1',
                type: 'guided',
                title: 'টপ রো একক কি',
                instruction: 'হোম রো থেকে আঙুল উপরে তুলে টপ রো কি চাপুন।',
                items: ['ঙ', 'র', 'ট', 'ে', 'য', 'ু', 'ি', 'ো', 'প'],
                requiredAccuracy: 90,
              },
              {
                id: 'sec-1-1-2',
                type: 'word',
                title: 'টপ রো শব্দমালা',
                instruction: 'টপ রো বর্ণ দিয়ে গঠিত শব্দ টাইপ করুন।',
                items: ['রুটি', 'পিঠ', 'পুঁই', 'ক্ষীর', 'পৈতে', 'পর', 'পট', 'পিঠ', 'পুড়', 'পুর', 'পীর', 'টুপ', 'টিপ', 'রূপ', 'রীতি', 'রুই'],
                requiredAccuracy: 92,
              },
            ],
          },
          {
            id: 'lesson-1-2',
            title: 'BR-01: বটম রো অক্ষর ও শব্দ',
            subtitle: 'Bottom Row Key Practice',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'টপ রো ও বটম রো পরিচিতি',
            description: 'বটম রো-এর ত, চ, দ, ব, ন, ম, থ, ছ, ধ, ভ, ণ বর্ণগুলো এবং শব্দ অনুশীলন করুন।',
            skills: ['bottom-row-keys', 'bottom-row-words'],
            prerequisites: ['lesson-1-1'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-2-1',
                type: 'guided',
                title: 'বটম রো একক কি',
                instruction: 'হোম রো থেকে আঙুল নিচে নামিয়ে বটম রো কি চাপুন।',
                items: ['ত', 'চ', 'দ', 'ব', 'ন', 'ম', 'থ', 'ছ', 'ধ', 'ভ', 'ণ'],
                requiredAccuracy: 90,
              },
              {
                id: 'sec-1-2-2',
                type: 'word',
                title: 'বটম রো সমৃদ্ধ শব্দ',
                instruction: 'বটম রো বর্ণ সমৃদ্ধ শব্দগুলো টাইপ করুন।',
                items: ['তথ্য', 'তব', 'বদ', 'মন', 'বন', 'ভব', 'ধন', 'নদ', 'দম', 'নব', 'মদ', 'বধ', 'ছন্দ', 'বন্ধ', 'মধ্য', 'ভবন', 'দম্ভ', 'দ্বন্দ', 'চন্দন', 'মন্থন'],
                requiredAccuracy: 92,
              },
            ],
          },
          {
            id: 'lesson-1-3',
            title: 'MR-01: রো মিক্সিং ১ (Home + Top + Bottom)',
            subtitle: 'Multi-Row Transition Practice',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'টপ রো ও বটম রো পরিচিতি',
            description: 'তিনটি সারির বর্ণ একত্রে মিলিয়ে বাস্তবিক টাইপিং শুরু করুন।',
            skills: ['row-mixing'],
            prerequisites: ['lesson-1-2'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-3-1',
                type: 'mixed',
                title: 'হোম ও টপ রো সংমিশ্রণ',
                instruction: 'হোম ও টপ রো-এর শব্দগুলো মিলিয়ে টাইপ করুন।',
                items: ['সারি', 'গোটি', 'রেখা', 'পুকুর', 'রুটি', 'পিঠ', 'ক্ষীর', 'সদাই', 'কদম', 'জলবন', 'চন্দন', 'মনন', 'দমন', 'বচন'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-1-3-2',
                type: 'mastery',
                title: 'অল রো মিক্সড চ্যালেন্জ',
                instruction: 'তিন রো-এর মিশ্রণে গঠিত শব্দ ও বাক্য টেস্ট।',
                items: ['সাদা', 'বাংলা', 'মানুষ', 'জীবন', 'বনের কাছে নদী চলে। নদীতে জলের ঢেউ নাচে। মানুষ ও বন একত্রে বাঁচে। সত্য ও সুন্দর জীবন গড়ি।'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 2: KAR SIGNS (কার-চিহ্ন) & VOWEL PATTERNS ───────────────
  {
    level: 2,
    title: 'কার-চিহ্ন ও স্বরবর্ণের রূপ (Vowel Signs — Kar)',
    tagline: 'বাংলা ১০টি কার-চিহ্ন এবং ব্যঞ্জনের সাথে সংমিশ্রণ',
    description: 'আ-কার থেকে ঔ-কার পর্যন্ত প্রতিটি কার-চিহ্ন এককভাবে, প্যাটার্নে এবং শব্দে টাইপ করুন।',
    badge: '🌸',
    modules: [
      {
        id: 'mod-2-1',
        level: 2,
        title: 'কার-চিহ্ন পরিচিতি ও প্যাটার্ন',
        description: 'কার-চিহ্নের নিয়ম ও বহু-ব্যঞ্জন সংমিশ্রণ',
        lessons: [
          {
            id: 'lesson-2-1',
            title: 'KAR-01: স্বরচিহ্ন Stage A (আ, ই, ঈ, উ, ঊ, ঋ)',
            subtitle: 'হ্রস্ব ও দীর্ঘ কার অনুশীলনী',
            level: 2,
            moduleId: 'mod-2-1',
            moduleTitle: 'কার-চিহ্ন পরিচিতি ও প্যাটার্ন',
            description: 'া, ি, ী, ু, ূ, ৃ কারগুলোর সাহায্যে ব্যঞ্জনবর্ণ যুক্ত করা শিখুন।',
            skills: ['kar-a', 'kar-i', 'kar-ee', 'kar-u', 'kar-oo', 'kar-ri'],
            prerequisites: ['lesson-1-3'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-2-1-1',
                type: 'pattern',
                title: 'আ-কার ও ই-কার প্যাটার্ন',
                instruction: 'ব্যঞ্জনের পর কার-চিহ্ন টাইপ করুন।',
                items: ['কা', 'খা', 'গা', 'ঘা', 'চা', 'কি', 'গি', 'চি', 'জি', 'টি', 'দি', 'নি', 'পি', 'বি', 'মি', 'রি', 'লি', 'সি'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-2-1-2',
                type: 'pattern',
                title: 'ঈ, উ, ঊ ও ঋ-কার প্যাটার্ন',
                instruction: 'দীর্ঘ কারগুলোর সঠিক কীবোর্ড প্রেস শিখুন।',
                items: ['কী', 'গী', 'চী', 'জী', 'কু', 'খু', 'গু', 'চু', 'জু', 'টু', 'দু', 'নু', 'পু', 'কূ', 'গূ', 'দূ', 'কৃ', 'গৃহ'],
                requiredAccuracy: 92,
              },
            ],
          },
          {
            id: 'lesson-2-2',
            title: 'KAR-02: স্বরচিহ্ন Stage B (ে, ৈ, ো, ৌ)',
            subtitle: 'এ-কার, ঐ-কার, ও-কার ও ঔ-কার',
            level: 2,
            moduleId: 'mod-2-1',
            moduleTitle: 'কার-চিহ্ন পরিচিতি ও প্যাটার্ন',
            description: 'ে, ৈ, ো, ৌ কারগুলো উচ্চারণ ও কীবোর্ড ইনপুট অনুযায়ী চর্চা করুন।',
            skills: ['kar-e', 'kar-oi', 'kar-o', 'kar-ou'],
            prerequisites: ['lesson-2-1'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-2-2-1',
                type: 'pattern',
                title: 'এ-কার ও ঐ-কার',
                instruction: 'কীবোর্ডে ে এবং ৈ টাইপ করুন।',
                items: ['কে', 'খে', 'গে', 'চে', 'জে', 'টে', 'দে', 'নে', 'পে', 'কৈ', 'গৈ', 'দৈ', 'নৈ', 'পৈ', 'বৈ', 'মৈ'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-2-2-2',
                type: 'pattern',
                title: 'ও-কার ও ঔ-কার',
                instruction: 'ো ও ৌ চিহ্নের সঠিক কি সংমিশ্রণ।',
                items: ['কো', 'গো', 'চো', 'জো', 'টো', 'দো', 'নো', 'পো', 'কৌ', 'গৌ', 'দৌ', 'নৌ', 'পৌ', 'মৌ'],
                requiredAccuracy: 92,
              },
            ],
          },
          {
            id: 'lesson-2-3',
            title: 'KAR-03: একটা কার → বহু ব্যঞ্জন (Pattern Building)',
            subtitle: 'Pattern Building & Kar-Word Mastery',
            level: 2,
            moduleId: 'mod-2-1',
            moduleTitle: 'কার-চিহ্ন পরিচিতি ও প্যাটার্ন',
            description: 'একটি নির্দিষ্ট কার চিহ্ন ব্যবহার করে বহু ব্যঞ্জনবর্ণ টাইপ করার প্যাটার্ন গড়ি।',
            skills: ['kar-patterns', 'kar-words'],
            prerequisites: ['lesson-2-2'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-2-3-1',
                type: 'pattern',
                title: 'ই-কার ও আ-কার প্যাটার্ন ড্রিল',
                instruction: 'একই কার বিভিন্ন ব্যঞ্জনে প্রয়োগ করার দ্রুততা অর্জন।',
                items: ['কি', 'গি', 'চি', 'জি', 'টি', 'দি', 'নি', 'পি', 'বি', 'মি', 'রি', 'লি', 'সি', 'কা', 'কি', 'কী', 'কু', 'কূ', 'কৃ', 'কে', 'কৈ', 'কো', 'কৌ'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-2-3-2',
                type: 'word',
                title: 'কার-যুক্ত বাস্তব শব্দমালা',
                instruction: 'দৈনন্দিন কার-যুক্ত বাংলা শব্দ টাইপ করুন।',
                items: ['দিন', 'মাটি', 'নদী', 'বিজয়', 'খুশি', 'ফুল', 'নতুন', 'মেঘ', 'আলো', 'নৌকা', 'সকাল', 'আকাশ', 'বাতাস', 'জীবন', 'মাথা', 'পাখি', 'মাছ', 'পানি'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 3: HASANTA (হসন্ত) & BASIC CONJUNCTS ────────────────────
  {
    level: 3,
    title: 'হসন্ত ও ব্যঞ্জন দ্বিত্ব (Hasanta & Doubled Consonants)',
    tagline: 'হসন্ত (্) এর ভূমিকা এবং দ্বিত্ব ব্যঞ্জন গঠন',
    description: 'বাংলা টাইপিংয়ে হসন্তের সঠিক ব্যবহার ও মৌলিক দ্বিত্ব ব্যঞ্জন টাইপ করা শিখুন।',
    badge: '⚡',
    modules: [
      {
        id: 'mod-3-1',
        level: 3,
        title: 'হসন্ত কোর্স (HAS-01 থেকে HAS-05)',
        description: 'একক হসন্ত ও ব্যঞ্জন দ্বিত্ব গঠন',
        lessons: [
          {
            id: 'lesson-3-1',
            title: 'HAS-01: একক হসন্ত ও হসন্তের অবস্থান',
            subtitle: 'Hasant (্) Basics',
            level: 3,
            moduleId: 'mod-3-1',
            moduleTitle: 'হসন্ত কোর্স (HAS-01 থেকে HAS-05)',
            description: 'ব্যঞ্জনবর্ণের নিচে হসন্ত চিহ্ন দেওয়ার নিয়ম শিখুন (H key / Hasant Key)।',
            skills: ['hasanta-single'],
            prerequisites: ['lesson-2-3'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-3-1-1',
                type: 'guided',
                title: 'একক হসন্ত অনুশীলন',
                instruction: 'ব্যঞ্জনবর্ণের সাথে হসন্ত টাইপ করুন।',
                items: ['ক্', 'ত্', 'ন্', 'স্', 'প্', 'ম্', 'ত্', 'ক্', 'ন্'],
                requiredAccuracy: 92,
              },
            ],
          },
          {
            id: 'lesson-3-2',
            title: 'HAS-02: দ্বিত্ব ব্যঞ্জন (kk, tt, nt, nd)',
            subtitle: 'Doubled & Common Hasanta Combos',
            level: 3,
            moduleId: 'mod-3-1',
            moduleTitle: 'হসন্ত কোর্স (HAS-01 থেকে HAS-05)',
            description: 'ক্ক, ক্ত, ন্ত, ন্দ, ম্প এর মতো জনপ্রিয় হসন্ত সংযোগ টাইপ করুন।',
            skills: ['hasanta-doubled'],
            prerequisites: ['lesson-3-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-3-2-1',
                type: 'pattern',
                title: 'সহজ হসন্ত সংযোগ',
                instruction: 'প্রথম বর্ণ + হসন্ত + দ্বিতীয় বর্ণ টাইপ করুন।',
                items: ['ক্ক', 'ক্ত', 'ন্ত', 'ন্দ', 'ম্প', 'ম্ব', 'ন্ত', 'ন্দ', 'ক্ত'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-3-2-2',
                type: 'word',
                title: 'হসন্ত সংযোগযুক্ত শব্দ',
                instruction: 'শব্দে হসন্ত সংযোগের প্রয়োগ।',
                items: ['পাকা', 'পাক্কা', 'রক্ত', 'শান্ত', 'আনন্দ', 'কম্পন', 'লম্বা', 'সন্তান', 'বক্তব্য'],
                requiredAccuracy: 94,
              },
            ],
          },
          {
            id: 'lesson-3-3',
            title: 'HAS-03 & 04: স-বর্গীয়, ষ-বর্গীয় ও শ-বর্গীয় সংযোগ',
            subtitle: 'S-Group & Sh-Group Conjuncts',
            level: 3,
            moduleId: 'mod-3-1',
            moduleTitle: 'হসন্ত কোর্স (HAS-01 থেকে HAS-05)',
            description: 'স্ট, স্থ, স্ক, স্প, ষ্ট, ষ্ঠ, শ্চ, ঞ্চ সংযোগগুলোর নিবিড় চর্চা।',
            skills: ['hasanta-s-group'],
            prerequisites: ['lesson-3-2'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-3-3-1',
                type: 'pattern',
                title: 'স, ষ ও শ যুক্তবর্ণ',
                instruction: 'স+ট (স্ট), স+থ (স্থ), ষ+ট (ষ্ট), শ+চ (শ্চ) টাইপ করুন।',
                items: ['স্ট', 'স্থ', 'স্ক', 'স্প', 'ষ্ট', 'ষ্ঠ', 'শ্চ', 'ঞ্চ'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-3-3-2',
                type: 'word',
                title: 'বাস্তব শব্দ অনুশীলন',
                instruction: 'স্টেশন, স্থান, কষ্ট, মিষ্টি, নিশ্চয়, সঞ্চয় শব্দ টাইপ করুন।',
                items: ['স্টেশন', 'স্থান', 'স্কুল', 'স্পষ্ট', 'কষ্ট', 'মিষ্টি', 'নিশ্চয়', 'সঞ্চয়', 'অনুষ্ঠান'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 4: FOLA (ফলা) & CONSONANT MODIFIERS ─────────────────────
  {
    level: 4,
    title: 'ফলা কোর্স (Fola: র, য, ল, রেফ, ব, ম-ফলা)',
    tagline: 'বাংলা টাইপিংয়ের গুরুত্বপূর্ণ ফলা পরিচিতি ও প্রয়োগ',
    description: 'র-ফলা, য-ফলা, ল-ফলা, রেফ, ব-ফলা এবং ম-ফলা আলাদা ক্যাটাগরিতে শিখুন।',
    badge: '🔮',
    modules: [
      {
        id: 'mod-4-1',
        level: 4,
        title: 'ফলা মডিউল (Dedicated Fola Module)',
        description: 'সকল প্রকার ফলা ও ফলা+কার সংমিশ্রণ',
        lessons: [
          {
            id: 'lesson-4-1',
            title: 'FOLA-01: র-ফলা (্ + র) ও র-ফলা+কার',
            subtitle: 'Ra-fola Practice',
            level: 4,
            moduleId: 'mod-4-1',
            moduleTitle: 'ফলা মডিউল (Dedicated Fola Module)',
            description: 'ক্র, গ্র, প্র, ব্র, ত্র, দ্র এবং কার-যুক্ত রূপ (ক্রি, গ্রা, প্রে, ত্রু) শিখুন।',
            skills: ['fola-ra'],
            prerequisites: ['lesson-3-3'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-4-1-1',
                type: 'pattern',
                title: 'র-ফলা প্যাটার্ন',
                instruction: 'বর্ণ + হসন্ত + র টাইপ করে র-ফলা তৈরি করুন।',
                items: ['ক্র', 'গ্র', 'প্র', 'ব্র', 'ত্র', 'দ্র', 'ক্রি', 'গ্রা', 'প্রে', 'ত্রু', 'শ্রে'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-4-1-2',
                type: 'word',
                title: 'র-ফলাযুক্ত শব্দ',
                instruction: 'গ্রাম, প্রাতঃ, ব্রত, ছাত্র, দ্রুত, প্রেম শব্দগুলো টাইপ করুন।',
                items: ['গ্রাম', 'প্রাতঃ', 'ব্রত', 'ছাত্র', 'দ্রুত', 'প্রেম', 'ক্রীড়া', 'প্রতিনিধি', 'শ্রাবণ'],
                requiredAccuracy: 94,
              },
            ],
          },
          {
            id: 'lesson-4-2',
            title: 'FOLA-02: য-ফলা (্ + য / ্য) ও য-ফলা+কার',
            subtitle: 'Ja-fola Practice',
            level: 4,
            moduleId: 'mod-4-1',
            moduleTitle: 'ফলা মডিউল (Dedicated Fola Module)',
            description: 'ক্য, ব্য, গ্য, দ্য, ন্য, পyd এবং কার-যুক্ত রূপ অনুশীলন করুন।',
            skills: ['fola-ja'],
            prerequisites: ['lesson-4-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-4-2-1',
                type: 'pattern',
                title: 'য-ফলা প্যাটার্ন',
                instruction: 'বর্ণ + Z key (্য) অথবা বর্ণ + হসন্ত + য টাইপ করুন।',
                items: ['ক্য', 'ব্য', 'গ্য', 'দ্য', 'ন্য', 'প্য', 'ব্যা', 'দ্যা', 'ন্যা'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-4-2-2',
                type: 'word',
                title: 'য-ফলাযুক্ত শব্দ',
                instruction: 'বাক্য,ব্যবসায়, ভাগ্য, সত্য, জন্য, ব্যায়াম শব্দ টাইপ করুন।',
                items: ['বাক্য', 'ব্যবসায়', 'ভাগ্য', 'সত্য', 'জন্য', 'ব্যায়াম', 'বিদ্যা', 'সন্ধ্যা', 'ধন্যবাদ'],
                requiredAccuracy: 94,
              },
            ],
          },
          {
            id: 'lesson-4-3',
            title: 'FOLA-03: রেফ (র + ্ + বর্ণ) ও ল/ব/ম-ফলা',
            subtitle: 'Ref & Other Fola Variations',
            level: 4,
            moduleId: 'mod-4-1',
            moduleTitle: 'ফলা মডিউল (Dedicated Fola Module)',
            description: 'রেফ (র্ক, র্গ, র্ত, র্দ) এবং ল-ফলা (ক্ল, গ্ল, প্ল), ব-ফলা (স্ব, ত্ব) টাইপ করা শিখুন।',
            skills: ['fola-ref', 'fola-la-ba-ma'],
            prerequisites: ['lesson-4-2'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-4-3-1',
                type: 'pattern',
                title: 'রেফ ও অন্যান্য ফলা প্যাটার্ন',
                instruction: 'র + হসন্ত + বর্ণ দিয়ে রেফ টাইপ করা হয়।',
                items: ['র্ক', 'র্গ', 'র্ত', 'র্দ', 'র্ম', 'ক্ল', 'গ্ল', 'প্ল', 'স্ব', 'দ্ব', 'ত্ব', 'স্ম', 'ম্ম'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-4-3-2',
                type: 'word',
                title: 'রেফ ও ফলা শব্দমালা',
                instruction: 'তর্ক, বর্গ, পর্বত, ধর্ম, ক্লাস, স্বাধীন, আত্ম টাইপ করুন।',
                items: ['তর্ক', 'বর্গ', 'পর্বত', 'ধর্ম', 'ক্লাস', 'গ্লানি', 'স্বাধীন', 'দ্বার', 'মহত্ত্ব', 'আত্মা', 'সম্মান'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 5: CONJUNCTS (যুক্তাক্ষর) BY DIFFICULTY & FAMILY ───────
  {
    level: 5,
    title: 'যুক্তাক্ষর মাস্টারক্লাস (Conjuncts Hierarchy)',
    tagline: 'সহজ, মাঝারি, কঠিন ও অতি কঠিন যুক্তাক্ষরের ক্রমান্বয়িক পাঠ',
    description: 'সহজ থেকে শুরু করে ক্ষ, জ্ঞ, হ্ম, ক্ষ্ম, ষ্ক্র এর মতো জটিল যুক্তবর্ণ আয়ত্ত করুন।',
    badge: '👑',
    modules: [
      {
        id: 'mod-5-1',
        level: 5,
        title: 'যুক্তাক্ষর সমাহার',
        description: 'ডিফিকাল্টি ও ফ্যামিলি অনুযায়ী বিভক্ত পাঠ',
        lessons: [
          {
            id: 'lesson-5-1',
            title: 'CONJ-01: সহজ ও মাঝারি যুক্তাক্ষর',
            subtitle: 'Easy & Medium Conjuncts',
            level: 5,
            moduleId: 'mod-5-1',
            moduleTitle: 'যুক্তাক্ষর সমাহার',
            description: 'ক্ত, ন্ত, ন্দ, ত্র, ক্র, গ্র, প্র, দ্র যুক্তাক্ষরগুলো দ্রুত টাইপ করুন।',
            skills: ['conjunct-easy-medium'],
            prerequisites: ['lesson-4-3'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-5-1-1',
                type: 'pattern',
                title: 'সহজ-মাঝারি যুক্তাক্ষর ড্রিল',
                instruction: 'হসন্তের মাধ্যমে সঠিক যুক্তবর্ণ তৈরি করুন।',
                items: ['ক্ত', 'ন্ত', 'ন্দ', 'ত্র', 'ক্র', 'গ্র', 'প্র', 'দ্র', 'ঙ্গ', 'ঙ্ক'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-5-1-2',
                type: 'word',
                title: 'শব্দে প্রয়োগ',
                instruction: 'শক্তি, প্রাপ্তি, কেন্দ্র, অঙ্গ, অঙ্ক শব্দ টাইপ করুন।',
                items: ['শক্তি', 'প্রাপ্তি', 'কেন্দ্র', 'অঙ্গ', 'অঙ্ক', 'প্রান্ত', 'ক্রান্তি', 'নিয়ন্ত্রণ'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-5-2',
            title: 'CONJ-02: কঠিন ও বিশেষ যুক্তাক্ষর (ক্ষ, জ্ঞ, শ্র, হ্ম)',
            subtitle: 'Hard & Special Conjuncts',
            level: 5,
            moduleId: 'mod-5-1',
            moduleTitle: 'যুক্তাক্ষর সমাহার',
            description: 'ক্ষ (ক+ষ বা Q key), জ্ঞ (জ+ঞ), শ্র (শ+র), হ্ম (হ+ম) এর সঠিক গঠন।',
            skills: ['conjunct-hard'],
            prerequisites: ['lesson-5-1'],
            estimatedMinutes: 5,
            difficulty: 5,
            sections: [
              {
                id: 'sec-5-2-1',
                type: 'pattern',
                title: 'বিশেষ যুক্ত বর্ণ',
                instruction: 'ক্ষ, জ্ঞ, শ্র, হ্ম কি সিকোয়েন্স লক্ষ্য করুন।',
                items: ['ক্ষ', 'জ্ঞ', 'শ্র', 'হ্ম', 'ক্ষি', 'জ্ঞা', 'শ্রু', 'হ্মো'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-5-2-2',
                type: 'word',
                title: 'বাস্তব শব্দ অনুশীলন',
                instruction: 'ক্ষমা, বিজ্ঞান,শ্রদ্ধা, ব্রাহ্মণ শব্দ টাইপ করুন।',
                items: ['ক্ষমা', 'শিক্ষা', 'বিজ্ঞান', 'জ্ঞান', 'শ্রদ্ধা', 'শ্রবণ', 'ব্রাহ্মণ', 'ব্রহ্মপুত্র'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-5-3',
            title: 'CONJ-03: খুব কঠিন যুক্তাক্ষর (ক্ষ্ম, ষ্ক্র, ন্ত্র, ম্প্রে)',
            subtitle: 'Very Hard Conjuncts & Exam Prep',
            level: 5,
            moduleId: 'mod-5-1',
            moduleTitle: 'যুক্তাক্ষর সমাহার',
            description: 'তিনটি বর্ণ বিশিষ্ট অতি জটিল যুক্তাক্ষর টাইপ করার দক্ষতা।',
            skills: ['conjunct-very-hard'],
            prerequisites: ['lesson-5-2'],
            estimatedMinutes: 6,
            difficulty: 6,
            sections: [
              {
                id: 'sec-5-3-1',
                type: 'pattern',
                title: 'ত্রি-বর্ণ যুক্তাক্ষর',
                instruction: 'তিনটি বর্ণ হসন্ত দিয়ে যুক্ত করে টাইপ করুন।',
                items: ['ক্ষ্ম', 'ষ্ক্র', 'ন্ত্র', 'ম্প্রে', 'স্ত্র', 'ন্ট্র'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-5-3-2',
                type: 'mastery',
                title: 'Conjunct Mastery Exam',
                instruction: '৯৫% নির্ভুলতায় যুক্তাক্ষর টেস্টটি সম্পন্ন করুন।',
                items: ['লক্ষণ', 'সূক্ষ্ম', 'নিষ্ক্রিয়', 'যন্ত্র', 'মন্ত্রণালয়', 'সম্পাদনা', 'অস্ট্রেলিয়া', 'কন্ট্রোল'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 6: NUMERALS (সংখ্যা) & SPECIAL BENGALI SIGNS ────────────
  {
    level: 6,
    title: 'সংখ্যা ও বিশেষ বর্ণ (Bengali Numerals & Special Characters)',
    tagline: 'বাংলা সংখ্যা ০-৯, সাল, তারিখ, টাকা এবং ঁ ং ঃ ় ৎ ড় ঢ় য়',
    description: 'সংখ্যা টাইপিং, তারিখ/মুদ্রা ফরম্যাটিং এবং বিরল বাংলা বর্ণসমূহের অনুশীলন।',
    badge: '🔢',
    modules: [
      {
        id: 'mod-6-1',
        level: 6,
        title: 'সংখ্যা ও বিশেষ চিহ্ন',
        description: 'সংখ্যা ও বিরল ক্যারেক্টার ড্রিল',
        lessons: [
          {
            id: 'lesson-6-1',
            title: 'NUM-01: বাংলা সংখ্যা ০-৯ ও সাল/তারিখ',
            subtitle: 'Bengali Digits & Dates',
            level: 6,
            moduleId: 'mod-6-1',
            moduleTitle: 'সংখ্যা ও বিশেষ চিহ্ন',
            description: '০ ১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯ সংখ্যাগুলো এবং ২০২৬, ১৩ নভেম্বর ২০০০ এর মতো তারিখ টাইপ করুন।',
            skills: ['numerals-digits', 'numerals-dates'],
            prerequisites: ['lesson-5-3'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-6-1-1',
                type: 'guided',
                title: 'সংখ্যা ০ থেকে ৯',
                instruction: 'কীবোর্ডের উপরের সারি থেকে বাংলা সংখ্যা টাইপ করুন।',
                items: ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯', '১', '২', '৩', '৪', '৫'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-6-1-2',
                type: 'word',
                title: 'সাল, তারিখ ও সংখ্যা গঠন',
                instruction: '২০২৬, ১৩ নভেম্বর ২০০০, ১৯৭১, ১৬ ডিসেম্বর টাইপ করুন।',
                items: ['২০২৬', '১৯৭১', '১৬ ডিসেম্বর', '২১ ফেব্রুয়ারি', '১৩ নভেম্বর ২০০০', '১২:৩০'],
                requiredAccuracy: 94,
              },
            ],
          },
          {
            id: 'lesson-6-2',
            title: 'NUM-02: টাকা, শতকরা ও সংকেত (৳ ১০০, ২৫%)',
            subtitle: 'Currency & Symbols',
            level: 6,
            moduleId: 'mod-6-1',
            moduleTitle: 'সংখ্যা ও বিশেষ চিহ্ন',
            description: '৳ ১০০, ২৫%, ১২:৩০, নম্বর-৫ এর মতো বাস্তব জীবনের সিম্বল টাইপিং।',
            skills: ['numerals-symbols'],
            prerequisites: ['lesson-6-1'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-6-2-1',
                type: 'word',
                title: 'মুদ্রা ও শতাংশ চিহ্ন',
                instruction: '৳ ১০০, ২৫%, ৫০ টাকা, নম্বর-১ টাইপ করুন।',
                items: ['৳ ১০০', '২৫%', '৫০ টাকা', '৳ ৫০০.০০', '১০০%', 'নম্বর-১'],
                requiredAccuracy: 94,
              },
            ],
          },
          {
            id: 'lesson-6-3',
            title: 'SPC-01: বিশেষ বর্ণ (ঁ ং ঃ ় ৎ ড় ঢ় য়)',
            subtitle: 'Special Bengali Characters',
            level: 6,
            moduleId: 'mod-6-1',
            moduleTitle: 'সংখ্যা ও বিশেষ চিহ্ন',
            description: 'চাঁদ, বাংলা, দুঃখ, হঠাৎ, বড়, আষাঢ়, আয় এর মতো শব্দে বিশেষ চিহ্নের প্রয়োগ।',
            skills: ['special-chars'],
            prerequisites: ['lesson-6-2'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-6-3-1',
                type: 'pattern',
                title: 'বিশেষ চিহ্ন একক ড্রিল',
                instruction: 'ঁ ং ঃ ় ৎ ড় ঢ় য় চিহ্নগুলো চিনুন ও টাইপ করুন।',
                items: ['ঁ', 'ং', 'ঃ', '়', 'ৎ', 'ড়', 'ঢ়', 'য়', 'চাঁ', 'বাং', 'দুঃ', 'হৎ', 'বড়', 'ঢ়'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-6-3-2',
                type: 'word',
                title: 'বিশেষ চিহ্ন যুক্ত শব্দ',
                instruction: 'চাঁদ, বাংলা, দুঃখ, হঠাৎ, গাড়ি, আষাঢ়, সময় শব্দ টাইপ করুন।',
                items: ['চাঁদ', 'পাঁচ', 'বাংলা', 'রং', 'দুঃখ', 'প্রাতঃকাল', 'হঠাৎ', 'উৎসব', 'গাড়ি', 'পাহাড়', 'আষাঢ়', 'সময়'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 7: COMMON BENGALI WORDS (নিত্যব্যবহার্য শব্দ corpus) ────
  {
    level: 7,
    title: 'শব্দ ভাণ্ডার (Common Bengali Words Corpus)',
    tagline: 'সর্বাধিক ব্যবহৃত বাংলা শব্দ corpus ও দৈর্ঘ্যভিত্তিক টাইপিং',
    description: '১ অক্ষর থেকে ৪+ অক্ষরের নিত্যব্যবহার্য শত শত শব্দের নিবিড় চর্চা।',
    badge: '📚',
    modules: [
      {
        id: 'mod-7-1',
        level: 7,
        title: 'দৈনন্দিন বাংলা শব্দমালা',
        description: 'ফ্রিকোয়েন্সি ও ক্যাটগরি অনুযায়ী শব্দ অনুশীলন',
        lessons: [
          {
            id: 'lesson-7-1',
            title: 'WORD-01: নিত্যব্যবহার্য সর্বনাম ও ক্রিয়াপদ',
            subtitle: 'High Frequency Words',
            level: 7,
            moduleId: 'mod-7-1',
            moduleTitle: 'দৈনন্দিন বাংলা শব্দমালা',
            description: 'আমি, আমরা, তুমি, আপনি, সে, এটা, ওটা, করে, হয়, আছে, নিয়ে, থেকে, জন্য, করা, হবে, ছিল।',
            skills: ['common-pronouns-verbs'],
            prerequisites: ['lesson-6-3'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-7-1-1',
                type: 'word',
                title: 'নিত্যদিনের বহুল ব্যবহৃত শব্দ',
                instruction: 'সবচেয়ে বেশি ব্যবহৃত বাংলা শব্দগুলো টাইপ করুন।',
                items: ['আমি', 'আমরা', 'তুমি', 'আপনি', 'সে', 'এটা', 'ওটা', 'করে', 'হয়', 'আছে', 'নিয়ে', 'থেকে', 'জন্য', 'করা', 'হবে', 'ছিল'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-7-2',
            title: 'WORD-02: ১, ২, ৩ ও ৪ অক্ষরের শব্দাবলি',
            subtitle: 'Word Length Progression',
            level: 7,
            moduleId: 'mod-7-1',
            moduleTitle: 'দৈনন্দিন বাংলা শব্দমালা',
            description: 'দৈর্ঘ্য অনুযায়ী সাজানো শব্দাবলি অনুশীলন করুন।',
            skills: ['word-length-tier'],
            prerequisites: ['lesson-7-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-7-2-1',
                type: 'word',
                title: '১ ও ২ অক্ষরের শব্দ',
                instruction: 'বই, জল, ফল, ঘর, বন, পথ, মত, নদ, জন, সব, কম, আম, জাম, গান, ধান টাইপ করুন।',
                items: ['বই', 'জল', 'ফল', 'ঘর', 'বন', 'পথ', 'মত', 'নদ', 'জন', 'সব', 'কম', 'আম', 'জাম', 'গান', 'ধান'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-7-2-2',
                type: 'word',
                title: '৩ ও ৪ অক্ষরের শব্দ',
                instruction: 'বাতাস, আকাশ, বাগান, কলম, কাগজ, বাংলাদেশ, বিশ্ববিদ্যালয় শব্দ টাইপ করুন।',
                items: ['বাতাস', 'আকাশ', 'বাগান', 'কলম', 'কাগজ', 'বিদ্যালয়', 'বাংলাদেশ', 'বিশ্ববিদ্যালয়', 'সফলতা'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-7-3',
            title: 'WORD-03: বিষয়ভিত্তিক শব্দ (শিক্ষা, প্রযুক্তি, অফিস, ব্যবসা)',
            subtitle: 'Themed Category Word Bank',
            level: 7,
            moduleId: 'mod-7-1',
            moduleTitle: 'দৈনন্দিন বাংলা শব্দমালা',
            description: 'শিক্ষা, প্রযুক্তি, অফিস, ব্যবসা ও সংবাদপত্রের বিশেষ শব্দমালা।',
            skills: ['themed-words'],
            prerequisites: ['lesson-7-2'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-7-3-1',
                type: 'word',
                title: 'অফিস ও প্রযুক্তি বিষয়ক শব্দ',
                instruction: 'কম্পিউটার, ইন্টারনেট, ফাইল, আবেদন, নিয়োগ, ব্যবস্থাপনা শব্দ টাইপ করুন।',
                items: ['কম্পিউটার', 'ইন্টারনেট', 'ফাইল', 'আবেদন', 'নিয়োগ', 'ব্যবস্থাপনা', 'প্রযুক্তি', 'সফটওয়্যার', 'যোগাযোগ', 'কর্মক্ষেত্র'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 8: SENTENCES (বাক্য) & PUNCTUATION (বিরামচিহ্ন) ─────────
  {
    level: 8,
    title: 'বাক্য গঠন ও বিরামচিহ্ন (Sentences & Punctuation)',
    tagline: 'বাংলা সকল বিরামচিহ্ন এবং বাক্যের দৈর্ঘ্য অনুযায়ী উন্নতি',
    description: "বাংলা সকল বিরামচিহ্ন এবং ছোট থেকে বড় বাক্য অনুশীলনের কোর্স।",
    badge: '✍️',
    modules: [
      {
        id: 'mod-8-1',
        level: 8,
        title: 'বিরামচিহ্ন ও বাক্য প্রকাশ',
        description: 'যতিচিহ্নের সঠিক নিয়ম ও বাক্য গঠন',
        lessons: [
          {
            id: 'lesson-8-1',
            title: 'PUNCT-01: বাংলা বিরামচিহ্ন আলাদা Lesson',
            subtitle: 'Punctuation Mark Practice',
            level: 8,
            moduleId: 'mod-8-1',
            moduleTitle: 'বিরামচিহ্ন ও বাক্য প্রকাশ',
            description: 'দাঁড়ি (।), কমা (,), প্রশ্নবোধক (?), বিস্ময়সূচক (!), হাইফেন, বন্ধনী ইত্যাদি টাইপিং।',
            skills: ['punctuation-marks'],
            prerequisites: ['lesson-7-3'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-8-1-1',
                type: 'guided',
                title: 'বিরামচিহ্ন চিহ্নিতকরণ',
                instruction: 'কীবোর্ড থেকে সরাসরি বিরামচিহ্নগুলো চাপুন।',
                items: ['।', ',', '?', '!', ':', ';', '-', '(', ')', '"', "'"],
                requiredAccuracy: 93,
              },
            ],
          },
          {
            id: 'lesson-8-2',
            title: 'SENT-01: সহজ ও মাঝারি বাক্য progression',
            subtitle: 'Sentence Progression 1 to 4',
            level: 8,
            moduleId: 'mod-8-1',
            moduleTitle: 'বিরামচিহ্ন ও বাক্য প্রকাশ',
            description: '১ম স্তর থেকে ৪থ স্তরের বাক্য প্রোগ্রেসন (আমি যাই → আমি আজ সকালে বাজারে গিয়েছিলাম।)।',
            skills: ['sentence-progression'],
            prerequisites: ['lesson-8-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-8-2-1',
                type: 'mixed',
                title: 'Sentence Level 1 & 2',
                instruction: 'ছোট ও মাঝারি বাক্য টাইপ করুন।',
                items: ['আমি যাই।', 'তুমি কি আসবে?', 'কেমন আছো?', 'আজ খুব ভালো দিন।', 'আমি আজ বাজারে যাই।'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-8-2-2',
                type: 'mixed',
                title: 'Sentence Level 3 & 4',
                instruction: 'জটিল যুক্তবর্ণ ও বিরামচিহ্ন সমৃদ্ধ পূর্ণ বাক্য।',
                items: ['আমি আজ সকালে বাজারে গিয়েছিলাম।', 'আমাদের মাতৃভাষা বাংলা আমাদের গর্ব।', 'প্রযুক্তি ব্যবহারের মাধ্যমে আমরা এগিয়ে যাচ্ছি!'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 9: PHRASES (শব্দগুচ্ছ) & TRANSITION PRACTICE ─────────────
  {
    level: 9,
    title: 'শব্দগুচ্ছ অনুশীলন (Phrase Practice & Transitions)',
    tagline: 'শব্দ ও স্পেসবারের মধ্যে মসৃণ ট্রানজিশন অর্জন',
    description: 'একক শব্দ থেকে স্পেস দিয়ে শব্দগুচ্ছ (Phrases) টাইপ করার দ্রুততা বাড়ান।',
    badge: '💬',
    modules: [
      {
        id: 'mod-9-1',
        level: 9,
        title: 'শব্দগুচ্ছ ও স্পেস ট্রানজিশন',
        description: '২ ও ৩ শব্দের প্রফেশনাল ফ্রেজ ড্রিল',
        lessons: [
          {
            id: 'lesson-9-1',
            title: 'PHR-01: ২ ও ৩ শব্দের শব্দগুচ্ছ',
            subtitle: 'Common Bengali Phrases',
            level: 9,
            moduleId: 'mod-9-1',
            moduleTitle: 'শব্দগুচ্ছ ও স্পেস ট্রানজিশন',
            description: 'আমি যাব, তুমি কি আসবে, আজ খুব ভালো দিন, সোনার বাংলা টাইপ করুন।',
            skills: ['phrase-transition'],
            prerequisites: ['lesson-8-2'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-9-1-1',
                type: 'mixed',
                title: 'শব্দগুচ্ছ টাইপিং',
                instruction: 'শব্দ শেষে সঠিক বৃদ্ধাঙ্গুলি দিয়ে স্পেসবার চাপুন।',
                items: ['আমি যাব', 'তুমি কি আসবে', 'কেমন আছো', 'আজ খুব ভালো দিন', 'সোনার বাংলা', 'আমাদের প্রিয় দেশ', 'শুভ সকাল', 'শুভরাত্রি'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-9-2',
            title: 'PHR-02: প্রফেশনাল ও অফিসিয়াল শব্দগুচ্ছ',
            subtitle: 'Professional Phrase Patterns',
            level: 9,
            moduleId: 'mod-9-1',
            moduleTitle: 'শব্দগুচ্ছ ও স্পেস ট্রানজিশন',
            description: 'শুভ অপরাহ্ন, ধন্যবাদান্তে, জরুরী বিজ্ঞপ্তি, বিনীত নিবেদন শব্দগুচ্ছ।',
            skills: ['professional-phrases'],
            prerequisites: ['lesson-9-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-9-2-1',
                type: 'mixed',
                title: 'অফিসিয়াল ফ্রেজ ড্রিল',
                instruction: 'অফিসিয়ালি ব্যবহৃত ফ্রেজগুলো দ্রুত টাইপ করুন।',
                items: ['শুভ অপরাহ্ন', 'ধন্যবাদান্তে', 'জরুরী বিজ্ঞপ্তি', 'বিনীত নিবেদন', 'যথাবিহিত সম্মান পূর্বক', 'আপনার বিশ্বস্ত'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 10: PARAGRAPHS (অনুচ্ছেদ) & LITERATURE ──────────────────
  {
    level: 10,
    title: 'অনুচ্ছেদ ও সাহিত্যধর্মী পাঠ (Paragraphs & Literature)',
    tagline: 'সহজ পাঠ, রবীন্দ্রনাথ, নজরুল ও আধুনিক সংবাদ অনুচ্ছেদ',
    description: 'দীর্ঘ প্যারাগ্রাফ, সাহিত্যিক বাক্য গঠন এবং মুক্ত টাইপিং অনুশীলন।',
    badge: '📖',
    modules: [
      {
        id: 'mod-10-1',
        level: 10,
        title: 'সাহিত্য ও গল্প অনুচ্ছেদ',
        description: 'রবীন্দ্রনাথ, নজরুল ও ক্লাসিক বাংলা সাহিত্য',
        lessons: [
          {
            id: 'lesson-10-1',
            title: 'LIT-01: সহজ পাঠ (রবীন্দ্রনাথ ঠাকুর)',
            subtitle: 'Sahaj Path Beginner Classics',
            level: 10,
            moduleId: 'mod-10-1',
            moduleTitle: 'সাহিত্য ও গল্প অনুচ্ছেদ',
            description: 'রবীন্দ্রনাথের "সহজ পাঠ" এর চিরচেনা ও সুন্দর বাক্যগুচ্ছ টাইপ করুন।',
            skills: ['sahaj-path'],
            prerequisites: ['lesson-9-2'],
            estimatedMinutes: 6,
            difficulty: 4,
            sections: [
              {
                id: 'sec-10-1-1',
                type: 'mixed',
                title: 'সহজ পাঠ অংশ ১',
                instruction: 'সহজ পাঠের অনুচ্ছেদটি টাইপ করুন।',
                items: ['বনে থাকে বাঘ। গাছে থাকে পাখি। জলে থাকে মাছ। ডালে আছে ফল। পাখি ফল খায়। পাখা মেলে ওড়ে। বাঘ আছে আম-বনে। গায়ে চাকা চাকা দাগ। পাখি বনে গান গায়। মাছ জলে খেলা করে।'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-10-2',
            title: 'LIT-02: সাহিত্য ও কবিতা (রবীন্দ্রনাথ ও নজরুল)',
            subtitle: 'Literature & Poetry Typing',
            level: 10,
            moduleId: 'mod-10-1',
            moduleTitle: 'সাহিত্য ও গল্প অনুচ্ছেদ',
            description: 'আমাদের ছোটো নদী, বিদ্রোহী, নির্ঝরের স্বপ্নভঙ্গ এর ক্লাসিক অংশ টাইপিং।',
            skills: ['poetry-literature'],
            prerequisites: ['lesson-10-1'],
            estimatedMinutes: 7,
            difficulty: 5,
            sections: [
              {
                id: 'sec-10-2-1',
                type: 'mixed',
                title: 'বিদ্রোহী ও ছোটো নদী কবিতাংশ',
                instruction: 'ছন্দ ও বিরামচিহ্ন বজায় রেখে টাইপ করুন।',
                items: ['আমাদের ছোটো নদী চলে বাঁকে বাঁকে, বৈশাখ মাসে তার হাঁটুজল থাকে। পার হয়ে যায় গোরু, পার হয় গাড়ি, দুই ধার উঁচু তার, ঢালু তার পাড়ি।', 'বল বীর- বল উন্নত মম শির! শির নেহারি আমারি, নতশির ওই শিখর হিমাদ্রির!'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 11: SPEED & PRECISION TRAINING ───────────────────────────
  {
    level: 11,
    title: 'গতি ও নির্ভুলতা স্প্রিন্ট (Speed & Precision Sprint)',
    tagline: '৩০+ GPM, ৫০+ GPM এবং ৯৮% precision রিইনফোর্সমেন্ট',
    description: 'নির্দিষ্ট সময় ও নির্ভুলতার টার্গেট নিয়ে টাইপিং স্পিড স্প্রিন্ট টেস্ট দিন।',
    badge: '⚡',
    modules: [
      {
        id: 'mod-11-1',
        level: 11,
        title: 'স্পিড স্প্রিন্ট চ্যালেঞ্জ',
        description: 'গতি ও এক্যুরেসি বুস্টার স্প্রিন্ট',
        lessons: [
          {
            id: 'lesson-11-1',
            title: 'SPD-01: ৩০ GPM স্পিড স্প্রিন্ট',
            subtitle: '30 GPM Target Drill',
            level: 11,
            moduleId: 'mod-11-1',
            moduleTitle: 'স্পিড স্প্রিন্ট চ্যালেঞ্জ',
            description: '৩০ গ্রাফিম পার মিনিট গতি অর্জন করার টাইমার টেস্ট।',
            skills: ['speed-30gpm'],
            prerequisites: ['lesson-10-2'],
            estimatedMinutes: 3,
            difficulty: 6,
            sections: [
              {
                id: 'sec-11-1-1',
                type: 'challenge',
                title: '৩০ GPM স্পিড টেস্ট',
                instruction: 'কমপক্ষে ৩০ GPM গতিতে টাইপ সম্পন্ন করুন।',
                items: ['টাইপিং একটি নিয়মিত অভ্যাসের বিষয়। যত বেশি অনুশীলন করা হবে, টাইপিং তত বেশি সহজ ও দ্রুত হবে।'],
                requiredAccuracy: 95,
                requiredWpm: 30,
              },
            ],
          },
          {
            id: 'lesson-11-2',
            title: 'SPD-02: ৫০ GPM হাই-স্পিড স্প্রিন্ট ও ৯৮% Precision',
            subtitle: '50 GPM & Precision Challenge',
            level: 11,
            moduleId: 'mod-11-1',
            moduleTitle: 'স্পিড স্প্রিন্ট চ্যালেঞ্জ',
            description: '৫০ GPM গতি এবং ৯৮% নির্ভুলতার সর্বোচ্চ দক্ষতা চ্যালেন্জ।',
            skills: ['speed-50gpm', 'high-precision'],
            prerequisites: ['lesson-11-1'],
            estimatedMinutes: 4,
            difficulty: 7,
            sections: [
              {
                id: 'sec-11-2-1',
                type: 'challenge',
                title: '৫০ GPM হাই স্পিড চ্যালেন্জ',
                instruction: '৯৮% নির্ভুলতায় ৫০ GPM গতি অর্জন করুন।',
                items: ['ডিজিটাল বাংলাদেশ গড়তে সঠিক ও দ্রুত বাংলা টাইপিংয়ের গুরুত্ব অপরিসীম। তথ্য প্রযুক্তির যুগে নিজের দক্ষতা বৃদ্ধি করুন।'],
                requiredAccuracy: 98,
                requiredWpm: 50,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 12: CERTIFICATION EXAM & EVALUATION ─────────────────────
  {
    level: 12,
    title: 'সরকারি ও চাকরির পরীক্ষা সিমুলেশন (Certification Exam)',
    tagline: 'সার্টিফাইড ফাইনাল এক্সাম ও স্ট্রিক্ট মোড ইভালুয়েশন',
    description: 'সকল লেভেলের দক্ষতা একত্রিত করে ফাইনাল টাইপিং সার্টিফিকেট অর্জন করুন।',
    badge: '🏆',
    modules: [
      {
        id: 'mod-12-1',
        level: 12,
        title: 'ফাইনাল সার্টিফিকেট পরীক্ষা',
        description: 'র্যান্ডমাইজড অল-স্কিল টাইপিং ইভালুয়েশন',
        lessons: [
          {
            id: 'lesson-12-1',
            title: 'EXAM-01: টাইপিং সার্টিফাইড ফাইনাল এক্সাম',
            subtitle: 'Comprehensive Certification Test',
            level: 12,
            moduleId: 'mod-12-1',
            moduleTitle: 'ফাইনাল সার্টিফিকেট পরীক্ষা',
            description: 'বর্ণমালা, কার, যুক্তাক্ষর, সংখ্যা, বিরামচিহ্ন ও অনুচ্ছেদের উপর চূড়ান্ত পরীক্ষা।',
            skills: ['final-certification'],
            prerequisites: ['lesson-11-2'],
            estimatedMinutes: 10,
            difficulty: 8,
            sections: [
              {
                id: 'sec-12-1-1',
                type: 'mastery',
                title: 'চূড়ান্ত ইভালুয়েশন টেস্ট',
                instruction: '৯৭% নির্ভুলতা নিয়ে সার্টিফিকেট পরীক্ষা সম্পন্ন করুন।',
                items: ['একদা এক বাঘের গলায় হাড় ফুটিয়াছিল। বাঘ বিস্তর চেষ্টা পাইল, কিছুতেই হাড় বাহির করিতে পারিল না; যন্ত্রণায় অস্থির হইয়া চারি দিকে দৌড়িয়া বেড়াইতে লাগিল। অবশেষে এক বক পুরস্কারের লোভে সম্মত হইল এবং বাঘের গলার ভিতর ঠোঁট দিয়ে হাড় বাহির করিল।'],
                requiredAccuracy: 97,
                requiredWpm: 35,
              },
            ],
          },
        ],
      },
    ],
  },
];

export function getCurriculumLessonById(id: string): CurriculumLesson | undefined {
  for (const level of CURRICULUM_LEVELS) {
    for (const module of level.modules) {
      const found = module.lessons.find(l => l.id === id);
      if (found) return found;
    }
  }
  return undefined;
}

export function getAllCurriculumLessons(): CurriculumLesson[] {
  return CURRICULUM_LEVELS.flatMap(lvl =>
    lvl.modules.flatMap(mod => mod.lessons)
  );
}