/**
 * Complete Curriculum Dataset (Levels 0 to 12)
 *
 * Fully implemented according to পরিকল্পনা.md:
 * - 7-Stage Home, Top, and Bottom Row Micro-lessons (HR-01 to HR-07, TR-01 to TR-07, BR-01 to BR-07)
 * - Row Mixing Module (Mixed 1 to 5)
 * - 2-Stage Kar System (Single Kar -> Multi Consonant -> Mixed Kar -> Kar + Conjunct)
 * - Hasanta Deep Dive (HAS-01 to HAS-05)
 * - Phola Families (Ra-fola, Ja-fola, La-fola, Ref, Ba/Ma-fola)
 * - Tiered Conjuncts (Easy, Medium, Hard, Very Hard)
 * - Bengali Numerals & Formats (0-9, currency, dates, percentages)
 * - Punctuation Course (Dandari, comma, question, exclamation, quotes)
 * - Common Bengali High-Frequency Words & Phrases
 * - Sentence Progression (Level 1 to 4)
 * - Literature, Sahaj Path & Office drafts
 * - Speed Sprints & Strict 5-min Government Exam Simulation
 */

import type { CurriculumLevel, CurriculumLesson } from './types';

export const CURRICULUM_LEVELS: CurriculumLevel[] = [
  // ── LEVEL 0: ORIENTATION ─────────────────────────────────────────
  {
    level: 0,
    title: 'পরিচিতি ও কীবোর্ড প্রস্তুতি (Orientation)',
    tagline: 'টাইপিং শেখার সঠিক নিয়ম ও কীবোর্ড লেআউট পরিচিতি',
    description: 'হাতের সঠিক পজিশন, কীবোর্ড লেআউট নির্বাচন এবং বেসিক টাইপিংয়ের নিয়মাবলী জানুন।',
    badge: '🚀',
    modules: [
      {
        id: 'mod-0-1',
        level: 0,
        title: 'কীবোর্ড ও টাইপিং নিয়মাবলী',
        description: 'হাতের সঠিক অবস্থান ও বেসিক কন্ট্রোল কি',
        lessons: [
          {
            id: 'lesson-0-1',
            title: 'টাইপিং প্রস্তুতি ও হাতের অবস্থান',
            subtitle: 'Home Row ও আঙুলের স্থান নির্ধারণ',
            level: 0,
            moduleId: 'mod-0-1',
            moduleTitle: 'কীবোর্ড ও টাইপিং নিয়মাবলী',
            description: 'কীবোর্ডে দুই হাতের ৮টি আঙুল কীভাবে স্থাপন করবেন এবং স্পেসবার চাপবেন তা শিখুন।',
            skills: ['home-position', 'space', 'backspace'],
            prerequisites: [],
            estimatedMinutes: 3,
            difficulty: 1,
            sections: [
              {
                id: 'sec-0-1-1',
                type: 'explanation',
                title: 'হাতের সঠিক পজিশন (Home Row Position)',
                instruction: 'বাম হাতের চার আঙুল A, S, D, F এবং ডান হাতের চার আঙুল J, K, L, ; কি-তে রাখুন। দুই বৃদ্ধাঙ্গুল থাকবে Spacebar-এর ওপর।',
                explanationText: 'টাইপিংয়ের মূল রহস্য হলো—স্ক্রিনের দিকে তাকিয়ে টাইপ করা, কীবোর্ডের দিকে না তাকিয়ে। প্রতিবার টাইপ করার পর আঙুলগুলো আবার Home Row-তে ফিরে আসবে।',
              },
              {
                id: 'sec-0-1-2',
                type: 'guided',
                title: 'বেসিক স্পেস ও অক্ষর অনুশীলন',
                instruction: 'আঙুলগুলো হোম রো-তে রেখে ধীরে ধীরে স্পেস ও ক্যারেক্টার অনুশীলন করুন।',
                items: ['ক', ' ', 'ল', ' ', 'স', ' ', 'া', ' '],
                requiredAccuracy: 90,
              },
              {
                id: 'sec-0-1-3',
                type: 'mastery',
                title: 'হোম রো পজিশন যাচাই পরীক্ষা',
                instruction: '৯৫% নির্ভুলতায় এই টেস্টটি সম্পন্ন করে পরবর্তী পাঠ আনলক করুন।',
                items: ['ক', 'ল', 'স', 'া', 'ড', 'ফ', 'গ', 'হ', 'জ'],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 1: সারি বিন্যাস ও রো মাইক্রো-কোর্স (ROW MICRO-LESSONS) ────────
  {
    level: 1,
    title: 'সারিভিত্তিক পাঠ ও রো-মিক্সিং (Row Mastery & Mixing)',
    tagline: 'হোম, টপ, বটম রো-এর ৭-ধাপের মাইক্রো-লেসন ও রো ট্রানজিশন',
    description: 'কী পজিশন থেকে শুরু করে দুই-কী কম্বো, সিলেবল, শব্দ, বাক্য এবং রো মিক্সিংয়ের পরিপূর্ণ কোর্স।',
    badge: '⌨️',
    modules: [
      // 1A: HOME ROW 7-STAGE COURSE
      {
        id: 'mod-1-1',
        level: 1,
        title: 'হোম রো পূর্ণাঙ্গ কোর্স (Home Row 7-Stage)',
        description: 'বাম হাত, ডান হাত, কম্বিনেশন, সিলেবল, শব্দ ও মাস্টারি টেস্ট',
        lessons: [
          {
            id: 'lesson-1-1',
            title: 'HR-01: প্রথম হাতের অক্ষর (া স ড ফ)',
            subtitle: 'বাম হাতের হোম কী পজিশন',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'হোম রো পূর্ণাঙ্গ কোর্স',
            description: 'A, S, D, F কি-এর া, স, ড, ফ অক্ষরের পরিচিতি ও দ্রুত আঙুল স্থাপন।',
            skills: ['home-left-keys'],
            prerequisites: ['lesson-0-1'],
            estimatedMinutes: 4,
            difficulty: 1,
            sections: [
              {
                id: 'sec-1-1-1',
                type: 'explanation',
                title: 'বাম হাতের হোম কী',
                instruction: 'A = া (কনিষ্ঠা), S = স (অনামিকা), D = ড (মধ্যমা), F = ফ (তর্জনী)।',
              },
              {
                id: 'sec-1-1-2',
                type: 'pattern',
                title: 'আইসোলেটেড প্যাটার্ন ড্রিল',
                items: ['া', 'স', 'ড', 'ফ', 'া', 'স', 'া', 'ফ', 'স', 'ড', 'স', 'ফ'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-1-1-3',
                type: 'mastery',
                title: 'HR-01 মাস্টারি টেস্ট',
                items: ['া', 'স', 'ড', 'ফ', 'ফা', 'সা', 'ডা', 'সফ', 'ফদ'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-2',
            title: 'HR-02: ডান পাশের হোম কী (গ ্ জ ক ল)',
            subtitle: 'ডান হাতের হোম কী ও হসন্ত পজিশন',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'হোম রো পূর্ণাঙ্গ কোর্স',
            description: 'G, H, J, K, L কি-এর গ, ্, জ, ক, ল অক্ষরগুলোর অনুশীলন।',
            skills: ['home-right-keys'],
            prerequisites: ['lesson-1-1'],
            estimatedMinutes: 4,
            difficulty: 2,
            sections: [
              {
                id: 'sec-1-2-1',
                type: 'pattern',
                title: 'ডান হাতের প্যাটার্ন',
                items: ['গ', '্', 'জ', 'ক', 'ল', 'গ', 'জ', 'ক', 'ল', 'গজ', 'কল'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-1-2-2',
                type: 'mastery',
                title: 'HR-02 মাস্টারি টেস্ট',
                items: ['গ', 'জ', 'ক', 'ল', 'গজ', 'কল', 'গল', 'জগ', 'লগ'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-3',
            title: 'HR-03: হোম রো মিক্স (সুষম ফ্রিকোয়েন্সি)',
            subtitle: 'উভয় হাতের সমন্বিত হোম রো প্যাটার্ন',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'হোম রো পূর্ণাঙ্গ কোর্স',
            description: 'বাম ও ডান হাতের হোম কী-গুলোর সুষম পুনরাবৃত্তি ও রিদম অনুশীলন।',
            skills: ['home-both-hands'],
            prerequisites: ['lesson-1-2'],
            estimatedMinutes: 4,
            difficulty: 2,
            sections: [
              {
                id: 'sec-1-3-1',
                type: 'pattern',
                title: 'ব্যালান্সড ফ্রিকোয়েন্সি ড্রিল',
                items: ['স', 'স', 'স', 'গ', 'গ', 'ফ', 'ফ', 'ড', 'ড', 'জ', 'ক', 'ক', 'ল', 'ল'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-1-3-2',
                type: 'mastery',
                title: 'HR-03 মাস্টারি টেস্ট',
                items: ['সগ', 'ফড', 'জক', 'লসা', 'গাফ', 'কজা', 'লাড'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-4',
            title: 'HR-04: দুই অক্ষরের কম্বিনেশন (সা, দা, গা, জু, কা, লা)',
            subtitle: 'হোম রো বর্ণ ও কারের সহজ জোড়',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'হোম রো পূর্ণাঙ্গ কোর্স',
            description: 'সা, দা, গা, কা, লা, ফা ইত্যাদি ২-কী কম্বিনেশন টাইপিং।',
            skills: ['home-combos-2'],
            prerequisites: ['lesson-1-3'],
            estimatedMinutes: 4,
            difficulty: 2,
            sections: [
              {
                id: 'sec-1-4-1',
                type: 'pattern',
                title: '২-অক্ষর কম্বো ড্রিল',
                items: ['সা', 'গা', 'কা', 'লা', 'ফা', 'ডা', 'জা', 'সা', 'গা', 'কা'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-4-2',
                type: 'mastery',
                title: 'HR-04 মাস্টারি টেস্ট',
                items: ['সা', 'গা', 'কা', 'লা', 'ফা', 'ডা', 'জা', 'কালা', 'গালা', 'সালা'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-5',
            title: 'HR-05: তিন অক্ষরের সিলেবল (সাদা, গাদা, জালা, দাদা)',
            subtitle: 'হোম রো সিলেবল ও প্রাকৃতিক প্যাটার্ন',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'হোম রো পূর্ণাঙ্গ কোর্স',
            description: 'সাদা, গাদা, জালা, দাদা, ফালা, কালা ইত্যাদিতে আসল শব্দের অনুভূতি পাওয়া।',
            skills: ['home-syllables-3'],
            prerequisites: ['lesson-1-4'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-5-1',
                type: 'word',
                title: 'হোম রো সিলেবল ড্রিল',
                items: ['সাদা', 'গাদা', 'জালা', 'দাদা', 'ফালা', 'কালা', 'গালা', 'ডালা'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-5-2',
                type: 'mastery',
                title: 'HR-05 মাস্টারি টেস্ট',
                items: ['সাদা', 'গাদা', 'জালা', 'দাদা', 'ফালা', 'কালা', 'গালা', 'ডালা'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-6',
            title: 'HR-06: বাস্তব হোম রো শব্দ (টিয়ার ১, ২, ৩)',
            subtitle: 'জল, ফল, গল থেকে সফল, ফসল ও জঙ্গল',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'হোম রো পূর্ণাঙ্গ কোর্স',
            description: 'সহজ থেকে যৌগিক হোম রো শব্দ: জল, ফল, সফল, ফসল, জঙ্গল, জলসা।',
            skills: ['home-tiered-words'],
            prerequisites: ['lesson-1-5'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-6-1',
                type: 'word',
                title: 'টিয়ার ১ ও ২ শব্দ (সহজ ও মাঝারি)',
                items: ['জল', 'ফল', 'গল', 'ডল', 'জাল', 'গাল', 'ফাল', 'হাল', 'শালা', 'জালা'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-6-2',
                type: 'word',
                title: 'টিয়ার ৩ শব্দ (যৌগিক)',
                items: ['সফল', 'ফসল', 'গজল', 'জঙ্গল', 'জলসা', 'সহসা', 'অলস', 'খলখল'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-6-3',
                type: 'mastery',
                title: 'HR-06 মাস্টারি টেস্ট',
                items: ['জল', 'ফল', 'সফল', 'ফসল', 'জঙ্গল', 'জলসা', 'সাদা', 'জাল'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-7',
            title: 'HR-07: হোম রো চূড়ান্ত মাস্টারি পরীক্ষা',
            subtitle: '৫০টি আইটেমের নিখুঁত মূল্যায়ন (৯৫%+ আবশ্যক)',
            level: 1,
            moduleId: 'mod-1-1',
            moduleTitle: 'হোম রো পূর্ণাঙ্গ কোর্স',
            description: 'হোম রো-এর সকল অক্ষর ও শব্দ মিলিয়ে চূড়ান্ত পরীক্ষা সম্পন্ন করুন।',
            skills: ['home-final-mastery'],
            prerequisites: ['lesson-1-6'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-7-1',
                type: 'mastery',
                title: 'হোম রো মাস্টারি টেস্ট',
                instruction: '৯৫% বা তার বেশি নির্ভুলতা অর্জন করলে হোম রো মাস্টার্ড হবে।',
                items: [
                  'জল', 'ফল', 'সাদা', 'গালা', 'সফল', 'ফসল', 'জাল', 'গাল',
                  'জালা', 'শালা', 'জঙ্গল', 'জলসা', 'কালা', 'ডালা', 'গজল', 'সহসা'
                ],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },

      // 1B: TOP ROW 7-STAGE COURSE
      {
        id: 'mod-1-2',
        level: 1,
        title: 'টপ রো পূর্ণাঙ্গ কোর্স (Top Row 7-Stage)',
        description: 'টপ রো অক্ষর, বিশেষ চিহ্ন, টপ শব্দ, হোম+টপ কম্বো ও মাস্টারি টেস্ট',
        lessons: [
          {
            id: 'lesson-1-8',
            title: 'TR-01: বাম হাতের টপ কী (ঙ র ট ে)',
            subtitle: 'W, R, T, E কি-এর সঠিক আঙুল',
            level: 1,
            moduleId: 'mod-1-2',
            moduleTitle: 'টপ রো পূর্ণাঙ্গ কোর্স',
            description: 'ঙ, র, ট, ে অক্ষরের আঙুল পজিশন ও নিয়মিত স্ট্রোক।',
            skills: ['top-left-keys'],
            prerequisites: ['lesson-1-7'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-8-1',
                type: 'pattern',
                title: 'বাম টপ প্যাটার্ন',
                items: ['ঙ', 'র', 'ট', 'ে', 'ঙ', 'র', 'ট', 'ে', 'রে', 'টে', 'রট'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-1-8-2',
                type: 'mastery',
                title: 'TR-01 মাস্টারি',
                items: ['ঙ', 'র', 'ট', 'ে', 'রঙ', 'টের', 'রট', 'রে'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-9',
            title: 'TR-02: ডান হাতের টপ কী (য ু ি ো প)',
            subtitle: 'Y, U, I, O, P কি-এর কার ও বর্ণ',
            level: 1,
            moduleId: 'mod-1-2',
            moduleTitle: 'টপ রো পূর্ণাঙ্গ কোর্স',
            description: 'য, ু, ি, ো, প অক্ষরের সঠিক ব্যবহার ও অনুশীলন।',
            skills: ['top-right-keys'],
            prerequisites: ['lesson-1-8'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-9-1',
                type: 'pattern',
                title: 'ডান টপ প্যাটার্ন',
                items: ['য', 'ু', 'ি', 'ো', 'প', 'পু', 'পি', 'পো', 'যো', 'জু'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-1-9-2',
                type: 'mastery',
                title: 'TR-02 মাস্টারি',
                items: ['য', 'ু', 'ি', 'ো', 'প', 'পর', 'পট', 'পিঠ', 'পুর'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-10',
            title: 'TR-03: বিরল ও বিশেষ টপ কী (ঁ ঃ ৈ ূ ী ৌ ৃ, ড় ঢ় য় ঞ)',
            subtitle: 'Shift সহযোগে বিশেষ স্বরচিহ্ন ও বর্ণ',
            level: 1,
            moduleId: 'mod-1-2',
            moduleTitle: 'টপ রো পূর্ণাঙ্গ কোর্স',
            description: 'টপ রো-এর শিফট কি সহযোগে বিরল চিহ্ন ও স্বরচিহ্ন টাইপ করা।',
            skills: ['top-special-keys'],
            prerequisites: ['lesson-1-9'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-1-10-1',
                type: 'pattern',
                title: 'বিশেষ টপ চিহ্ন প্যাটার্ন',
                items: ['ঁ', 'ঃ', 'ৈ', 'ূ', 'ী', 'ৌ', 'ৃ', 'ড়', 'ঢ়', 'য়', 'ঞ'],
                requiredAccuracy: 92,
              },
              {
                id: 'sec-1-10-2',
                type: 'mastery',
                title: 'TR-03 মাস্টারি',
                items: ['রঙ', 'পৈতে', 'ক্ষীর', 'পূজা', 'রীতির', 'চাঁদ', 'দুঃখ'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-11',
            title: 'TR-04: হোম + টপ মিশ্রিত কম্বো (সা, রি, গো, টি, রে)',
            subtitle: 'হোম ও টপ রো-এর মধ্যে সাবলীল চলাচল',
            level: 1,
            moduleId: 'mod-1-2',
            moduleTitle: 'টপ রো পূর্ণাঙ্গ কোর্স',
            description: 'হোম রো এবং টপ রো-এর অক্ষরের যৌথ সংমিশ্রণে দ্রুত ট্রানজিশন।',
            skills: ['home-top-mix'],
            prerequisites: ['lesson-1-10'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-11-1',
                type: 'pattern',
                title: 'হোম+টপ ট্রানজিশন ড্রিল',
                items: ['সা', 'রি', 'গো', 'টি', 'রে', 'পো', 'কা', 'রু', 'গে', 'পা'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-11-2',
                type: 'mastery',
                title: 'TR-04 মাস্টারি',
                items: ['সারি', 'গোরু', 'টিরে', 'পোকা', 'গাছ', 'পাখি', 'রুটি'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-12',
            title: 'TR-05: টপ রো শব্দভাণ্ডার (রুটি, পিঠ, পুঁই, ক্ষীর, পৈতে)',
            subtitle: 'টপ রো নির্ভর সমৃদ্ধ শব্দ তালিকা',
            level: 1,
            moduleId: 'mod-1-2',
            moduleTitle: 'টপ রো পূর্ণাঙ্গ কোর্স',
            description: 'রুটি, পিঠ, পুঁই, ক্ষীর, পৈতে, টোপর, রূপ, রীতি ইত্যাদি শব্দ।',
            skills: ['top-words'],
            prerequisites: ['lesson-1-11'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-1-12-1',
                type: 'word',
                title: 'টপ রো শব্দ ড্রিল',
                items: ['রুটি', 'পিঠ', 'পুঁই', 'ক্ষীর', 'পৈতে', 'টোপর', 'টুপ', 'টিপ', 'রীতি', 'রূপ'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-12-2',
                type: 'mastery',
                title: 'TR-05 মাস্টারি',
                items: ['রুটি', 'ক্ষীর', 'পুঁই', 'পৈতে', 'টোপর', 'পিঠ', 'রূপ', 'রীতি'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-13',
            title: 'TR-06: হোম + টপ বাক্য অনুশীলন',
            subtitle: 'হোম ও টপ রো সহযোগে পূর্ণ বাক্য',
            level: 1,
            moduleId: 'mod-1-2',
            moduleTitle: 'টপ রো পূর্ণাঙ্গ কোর্স',
            description: 'হোম ও টপ রো অক্ষরের সমন্বয়ে ছোট ও অর্থপূর্ণ বাক্য গঠন।',
            skills: ['top-sentences'],
            prerequisites: ['lesson-1-12'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-1-13-1',
                type: 'word',
                title: 'হোম+টপ বাক্য ড্রিল',
                items: [
                  'পাখি ফল খায়।',
                  'গাছে পাখি গান গায়।',
                  'জলে মাছ খেলা করে।',
                  'সাদা রুটি খাই।',
                ],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-13-2',
                type: 'mastery',
                title: 'TR-06 মাস্টারি',
                items: [
                  'পাখি ফল খায়।',
                  'গাছে পাখি গান গায়।',
                  'জলে মাছ খেলা করে।',
                  'সাদা রুটি খাই।',
                ],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-14',
            title: 'TR-07: টপ রো চূড়ান্ত মাস্টারি পরীক্ষা',
            subtitle: 'টপ রো দক্ষতা মূল্যায়ন (৯৫%+ আবশ্যক)',
            level: 1,
            moduleId: 'mod-1-2',
            moduleTitle: 'টপ রো পূর্ণাঙ্গ কোর্স',
            description: 'টপ রো-এর সকল বর্ণ, কার ও মিশ্রিত শব্দের মূল্যায়ন পরীক্ষা।',
            skills: ['top-final-mastery'],
            prerequisites: ['lesson-1-13'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-1-14-1',
                type: 'mastery',
                title: 'টপ রো মাস্টারি টেস্ট',
                items: [
                  'রুটি', 'ক্ষীর', 'পুঁই', 'গাছে পাখি গান গায়', 'পৈতে', 'টোপর', 'পাখি ফল খায়', 'জল ও মাছ'
                ],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },

      // 1C: BOTTOM ROW 7-STAGE COURSE
      {
        id: 'mod-1-3',
        level: 1,
        title: 'বটম রো পূর্ণাঙ্গ কোর্স (Bottom Row 7-Stage)',
        description: 'বটম রো বর্ণ, শিফট কী, বটম শব্দ, সর্ব-রো মিক্স ও মাস্টারি টেস্ট',
        lessons: [
          {
            id: 'lesson-1-15',
            title: 'BR-01: ত চ দ',
            subtitle: 'Z, X, C, V কি-এর বাম হাতের বটম কী',
            level: 1,
            moduleId: 'mod-1-3',
            moduleTitle: 'বটম রো পূর্ণাঙ্গ কোর্স',
            description: '্য, ত, চ, দ অক্ষরের অবস্থান ও সঠিক আঙুল ব্যবহার।',
            skills: ['bottom-left-keys'],
            prerequisites: ['lesson-1-14'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-15-1',
                type: 'pattern',
                title: 'ত চ দ প্যাটার্ন ড্রিল',
                items: ['ত', 'চ', 'দ', 'ত', 'চ', 'দ', 'তদ', 'চত', 'দচ', 'তচদ'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-1-15-2',
                type: 'mastery',
                title: 'BR-01 মাস্টারি',
                items: ['ত', 'চ', 'দ', 'চাঁদ', 'দান', 'তাল', 'চক'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-16',
            title: 'BR-02: ব ন ম',
            subtitle: 'B, N, M কি-এর তর্জনী ও মধ্যমা',
            level: 1,
            moduleId: 'mod-1-3',
            moduleTitle: 'বটম রো পূর্ণাঙ্গ কোর্স',
            description: 'ব, ন, ম অক্ষরের দ্রুত ও নির্ভুল টাইপিং অনুশীলন।',
            skills: ['bottom-mid-keys'],
            prerequisites: ['lesson-1-15'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-16-1',
                type: 'pattern',
                title: 'ব ন ম প্যাটার্ন',
                items: ['ব', 'ন', 'ম', 'বন', 'নব', 'মন', 'মব', 'নম', 'বম'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-1-16-2',
                type: 'mastery',
                title: 'BR-02 মাস্টারি',
                items: ['বন', 'মন', 'নব', 'বই', 'নদী', 'মাটি', 'মানব'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-17',
            title: 'BR-03: থ ছ ধ ভ ণ',
            subtitle: 'বটম রো-এর Shift কী সমন্বয়',
            level: 1,
            moduleId: 'mod-1-3',
            moduleTitle: 'বটম রো পূর্ণাঙ্গ কোর্স',
            description: 'Shift+X (থ), Shift+C (ছ), Shift+V (ধ), Shift+B (ভ), Shift+N (ণ) এর নিয়ম।',
            skills: ['bottom-shift-keys'],
            prerequisites: ['lesson-1-16'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-1-17-1',
                type: 'pattern',
                title: 'বটম শিফট প্যাটার্ন',
                items: ['থ', 'ছ', 'ধ', 'ভ', 'ণ', 'তথ্য', 'ছায়া', 'ধন', 'ভাত', 'গুণ'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-1-17-2',
                type: 'mastery',
                title: 'BR-03 মাস্টারি',
                items: ['তথ্য', 'ছাতা', 'ধনী', 'ভালো', 'বাণী', 'ছন্দ'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-18',
            title: 'BR-04: Home + Top + Bottom সর্ব-রো মিক্স',
            subtitle: 'সাদা, বাংলা, মানুষ, জীবন',
            level: 1,
            moduleId: 'mod-1-3',
            moduleTitle: 'বটম রো পূর্ণাঙ্গ কোর্স',
            description: 'তিনটি সারির অক্ষরের মসৃণ ও দ্রুত সমন্বিত টাইপিং।',
            skills: ['all-rows-combo'],
            prerequisites: ['lesson-1-17'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-1-18-1',
                type: 'word',
                title: 'সর্ব-রো মিশ্রিত শব্দ',
                items: ['সাদা', 'বাংলা', 'মানুষ', 'জীবন', 'সময়', 'দেশ', 'স্বাধীনতা', 'প্রকৃতি'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-18-2',
                type: 'mastery',
                title: 'BR-04 মাস্টারি',
                items: ['বাংলা', 'মানুষ', 'জীবন', 'স্বাধীনতা', 'সাদা', 'প্রকৃতি'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-19',
            title: 'BR-05: বটম-হেভি শব্দভাণ্ডার',
            subtitle: 'তথ্য, বন্ধ, চন্দন, মন্থন, ধন্য',
            level: 1,
            moduleId: 'mod-1-3',
            moduleTitle: 'বটম রো পূর্ণাঙ্গ কোর্স',
            description: 'বটম রো প্রাধান্যযুক্ত শব্দের টাইপিং দক্ষতা বৃদ্ধি।',
            skills: ['bottom-heavy-words'],
            prerequisites: ['lesson-1-18'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-1-19-1',
                type: 'word',
                title: 'বটম-হেভি শব্দ ড্রিল',
                items: ['তথ্য', 'তব', 'বচন', 'দমন', 'নন্দন', 'বন্ধন', 'চন্দন', 'মন্থন', 'ধন্য', 'নব্য'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-19-2',
                type: 'mastery',
                title: 'BR-05 মাস্টারি',
                items: ['তথ্য', 'চন্দন', 'মন্থন', 'বন্ধন', 'ধন্য', 'নন্দন', 'বচন'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-20',
            title: 'BR-06: সর্ব-রো সমন্বিত অনুচ্ছেদ',
            subtitle: 'বাস্তব তিন-রো টেক্সট ফ্লুয়েন্সি',
            level: 1,
            moduleId: 'mod-1-3',
            moduleTitle: 'বটম রো পূর্ণাঙ্গ কোর্স',
            description: 'সকল রো-এর বর্ণ সমন্বয়ে অনুচ্ছেদ টাইপিং।',
            skills: ['bottom-paragraph'],
            prerequisites: ['lesson-1-19'],
            estimatedMinutes: 6,
            difficulty: 5,
            sections: [
              {
                id: 'sec-1-20-1',
                type: 'word',
                title: 'অনুচ্ছেদ ড্রিল',
                items: [
                  'আমার সোনার বাংলা আমি তোমায় ভালোবাসি। চিরদিন তোমার আকাশ ও বাতাস আমার মনে আনন্দ দেয়।',
                  'মানুষের জীবন সাধনা ও অধ্যবসায়ের মাধ্যমে সুন্দর হয়ে ওঠে। নিয়মিত অনুশীলন টাইপিং গতি বাড়িয়ে দেয়।',
                ],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-1-20-2',
                type: 'mastery',
                title: 'BR-06 মাস্টারি',
                items: [
                  'আমার সোনার বাংলা আমি তোমায় ভালোবাসি। মানুষের জীবন সাধনা ও অধ্যবসায়ের মাধ্যমে সুন্দর হয়ে ওঠে।',
                ],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-21',
            title: 'BR-07: বটম রো চূড়ান্ত মাস্টারি পরীক্ষা',
            subtitle: 'বটম রো দক্ষতা যাচাই (৯৫%+ আবশ্যক)',
            level: 1,
            moduleId: 'mod-1-3',
            moduleTitle: 'বটম রো পূর্ণাঙ্গ কোর্স',
            description: 'বটম রো-এর সামগ্রিক দক্ষতা ও গতি যাচাই।',
            skills: ['bottom-final-mastery'],
            prerequisites: ['lesson-1-20'],
            estimatedMinutes: 5,
            difficulty: 5,
            sections: [
              {
                id: 'sec-1-21-1',
                type: 'mastery',
                title: 'বটম রো মাস্টারি টেস্ট',
                items: [
                  'তথ্য', 'বন্ধন', 'চন্দন', 'বাংলা', 'মানুষ', 'জীবন', 'ধন্য', 'স্বাধীনতা'
                ],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },

      // 1D: ROW MIXING MODULE (mixed-row-1 to 5)
      {
        id: 'mod-1-4',
        level: 1,
        title: 'রো মিক্সিং মডিউল (Row Mixing 1–5)',
        description: 'Home only, Home+Top, Home+Bottom, Top+Bottom এবং All Rows ট্রানজিশন',
        lessons: [
          {
            id: 'lesson-1-22',
            title: 'mixed-row-1: হোম রো স্পেশাল ড্রিল',
            subtitle: 'Home only বিশুদ্ধ গতি',
            level: 1,
            moduleId: 'mod-1-4',
            moduleTitle: 'রো মিক্সিং মডিউল',
            description: 'হোম রো-তে সর্বোচ্চ গতি ও রিল্যাক্সড আঙুল পজিশন।',
            skills: ['mix-home-only'],
            prerequisites: ['lesson-1-21'],
            estimatedMinutes: 4,
            difficulty: 2,
            sections: [
              {
                id: 'sec-1-22-1',
                type: 'word',
                title: 'হোম রো স্পিড ড্রিল',
                items: ['জল', 'ফল', 'সাদা', 'গালা', 'সফল', 'ফসল', 'জালা', 'শালা', 'হাল', 'ডালা'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-23',
            title: 'mixed-row-2: হোম + টপ ট্রানজিশন',
            subtitle: 'Home + Top উল্লম্ব আঙুল সঞ্চালন',
            level: 1,
            moduleId: 'mod-1-4',
            moduleTitle: 'রো মিক্সিং মডিউল',
            description: 'হোম ও টপ রো-এর মধ্যে দ্রুত হাত স্থানান্তরের সঠিক পদ্ধতি।',
            skills: ['mix-home-top'],
            prerequisites: ['lesson-1-22'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-23-1',
                type: 'word',
                title: 'হোম+টপ ড্রিল',
                items: ['পাখি', 'রুটি', 'গাছ', 'পিঠ', 'ক্ষীর', 'পোকা', 'সারি', 'গোরু'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-24',
            title: 'mixed-row-3: হোম + বটম ট্রানজিশন',
            subtitle: 'Home + Bottom নিচের দিকে রিচ',
            level: 1,
            moduleId: 'mod-1-4',
            moduleTitle: 'রো মিক্সিং মডিউল',
            description: 'হোম রো থেকে বটম রো-তে আঙুল বাড়িয়ে টাইপ করার নিখুঁত কৌশল।',
            skills: ['mix-home-bottom'],
            prerequisites: ['lesson-1-23'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-1-24-1',
                type: 'word',
                title: 'হোম+বটম ড্রিল',
                items: ['সাদা', 'বন', 'জল', 'মন', 'ফল', 'নদ', 'দান', 'তাল'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-25',
            title: 'mixed-row-4: টপ + বটম জাম্পিং',
            subtitle: 'Top + Bottom দীর্ঘ রিচ অনুশীলন',
            level: 1,
            moduleId: 'mod-1-4',
            moduleTitle: 'রো মিক্সিং মডিউল',
            description: 'টপ রো থেকে সরাসরি বটম রো-তে যাওয়ার চ্যালেঞ্জিং ড্রিল।',
            skills: ['mix-top-bottom'],
            prerequisites: ['lesson-1-24'],
            estimatedMinutes: 4,
            difficulty: 4,
            sections: [
              {
                id: 'sec-1-25-1',
                type: 'word',
                title: 'টপ+বটম ড্রিল',
                items: ['নদী', 'পাখি', 'পানি', 'রুটি', 'ভাত', 'মাটি', 'পাহাড়', 'মেঘ'],
                requiredAccuracy: 95,
              },
            ],
          },
          {
            id: 'lesson-1-26',
            title: 'mixed-row-5: সর্ব-রো ফ্লুয়েন্সি (All Rows)',
            subtitle: 'সকল সারির পূর্ণাঙ্গ মাস্টার ড্রিল',
            level: 1,
            moduleId: 'mod-1-4',
            moduleTitle: 'রো মিক্সিং মডিউল',
            description: 'হোম, টপ ও বটম রো মিলিয়ে যেকোনো বাংলা শব্দের দ্রুত টাইপিং।',
            skills: ['mix-all-rows'],
            prerequisites: ['lesson-1-25'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-1-26-1',
                type: 'mastery',
                title: 'রো মিক্সিং মাস্টার টেস্ট',
                items: ['বাংলাদেশ', 'মানুষ', 'জীবন', 'স্বাধীনতা', 'প্রকৃতি', 'পরিবার', 'সংস্কৃতি', 'শিক্ষা'],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 2: কার-চিহ্ন ২-স্তরের পাঠ (VOWEL SIGNS — KAR) ─────────────────
  {
    level: 2,
    title: 'কার চিহ্ন ২-স্তরের পাঠ (Vowel Signs — Kar)',
    tagline: 'এক কার → বহু ব্যঞ্জন এবং কার মিশ্রিত ও যুক্তাক্ষর সংযোগ',
    description: 'আ-কার থেকে ঔ-কার পর্যন্ত প্রতিটি কারের সুশৃঙ্খল বিন্যাস ও কার+যুক্তাক্ষরের নিবিড় ড্রিল।',
    badge: '🎯',
    modules: [
      {
        id: 'mod-2-1',
        level: 2,
        title: 'Stage A: একক কার অনুযায়ী অনুশীলন (Single Kar Focus)',
        description: 'এক কার → বহু ব্যঞ্জন প্যাটার্ন ও শব্দভাণ্ডার',
        lessons: [
          {
            id: 'lesson-2-1',
            title: 'আ-কার (া) ও ই-কার (ি)',
            subtitle: 'কা, খা, গা... ও কি, গি, চি, জি, দি...',
            level: 2,
            moduleId: 'mod-2-1',
            moduleTitle: 'Stage A: একক কার অনুযায়ী অনুশীলন',
            description: 'া ও ি কার দিয়ে ব্যঞ্জন রূপান্তর এবং দিন, মাটি, নদী, বিজয় শব্দ।',
            skills: ['kar-a', 'kar-i'],
            prerequisites: ['lesson-1-26'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-2-1-1',
                type: 'pattern',
                title: 'ি-কার প্যাটার্ন (এক কার → বহু ব্যঞ্জন)',
                items: ['কি', 'গি', 'চি', 'জি', 'টি', 'দি', 'নি', 'পি', 'বি', 'মি', 'রি', 'লি', 'সি'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-2-1-2',
                type: 'word',
                title: 'বাস্তব শব্দ ড্রিল',
                items: ['দিন', 'মাটি', 'নদী', 'বিজয়', 'চিনি', 'পাখি', 'পানি', 'কবি', 'ছবি'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-2-1-3',
                type: 'mastery',
                title: 'আ ও ই কার মাস্টারি',
                items: ['দিন', 'মাটি', 'বিজয়', 'নদী', 'পাখি', 'বাবা', 'মামা', 'চিনি'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-2-2',
            title: 'ঈ-কার (ী), উ-কার (ু) ও ঊ-কার (ূ)',
            subtitle: 'কী, দী, নী... ও কু, গু, চু, ফুল, দুধ, রূপ...',
            level: 2,
            moduleId: 'mod-2-1',
            moduleTitle: 'Stage A: একক কার অনুযায়ী অনুশীলন',
            description: 'দীর্ঘ ঈ, হ্রস্ব উ ও দীর্ঘ ঊ কারের সঠিক টাইপিং।',
            skills: ['kar-ee', 'kar-u', 'kar-oo'],
            prerequisites: ['lesson-2-1'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-2-2-1',
                type: 'pattern',
                title: 'ু ও ূ প্যাটার্ন ড্রিল',
                items: ['কু', 'কূ', 'গু', 'গূ', 'তু', 'তূ', 'দু', 'দূ', 'নু', 'নূ', 'পু', 'পূ', 'মু', 'মূ'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-2-2-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['ফুল', 'কূল', 'দুধ', 'দূর', 'রূপ', 'মূল্য', 'সূর্য', 'নূপুর', 'সুখ', 'মুখ'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-2-2-3',
                type: 'mastery',
                title: 'ঈ, উ, ঊ কার মাস্টারি',
                items: ['ফুল', 'দূর', 'রূপ', 'সূর্য', 'মূল্য', 'নদী', 'কীর্তি', 'দুধ'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-2-3',
            title: 'ঋ-কার (ৃ), এ-কার (ে) ও ঐ-কার (ৈ)',
            subtitle: 'কৃ, গৃহ, কে, গে, দেশ, বৈশাখ, কেমন...',
            level: 2,
            moduleId: 'mod-2-1',
            moduleTitle: 'Stage A: একক কার অনুযায়ী অনুশীলন',
            description: 'ঋ-কার (\\), এ-কার (e) ও ঐ-কার (Shift+E) এর নিয়ম।',
            skills: ['kar-ri', 'kar-e', 'kar-oi'],
            prerequisites: ['lesson-2-2'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-2-3-1',
                type: 'pattern',
                title: 'ৃ, ে, ৈ প্যাটার্ন',
                items: ['কৃ', 'গৃহ', 'তৃ', 'মৃ', 'কে', 'গে', 'তে', 'দে', 'কৈ', 'তৈ', 'সৈ'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-2-3-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['কৃষি', 'গৃহ', 'তৃণ', 'কেমন', 'দেশ', 'মেঘ', 'তৈরি', 'বৈশাখ', 'সৈনিক', 'ঐক্য'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-2-3-3',
                type: 'mastery',
                title: 'ঋ, এ, ঐ কার মাস্টারি',
                items: ['কৃষি', 'গৃহ', 'কেমন', 'দেশ', 'তৈরি', 'বৈশাখ', 'সৈনিক'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-2-4',
            title: 'ও-কার (ো) ও ঔ-কার (ৌ)',
            subtitle: 'কো, গো, তো, লোক, নৌকা, কৌতূহল...',
            level: 2,
            moduleId: 'mod-2-1',
            moduleTitle: 'Stage A: একক কার অনুযায়ী অনুশীলন',
            description: 'ও-কার (o) এবং ঔ-কার (Shift+O) এর ব্যবহার ও শব্দ।',
            skills: ['kar-o', 'kar-ou'],
            prerequisites: ['lesson-2-3'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-2-4-1',
                type: 'pattern',
                title: 'ো ও ৌ প্যাটার্ন',
                items: ['কো', 'কৌ', 'গো', 'গৌ', 'তো', 'তৌ', 'দো', 'দৌ', 'পো', 'পৌ', 'লো', 'লৌ'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-2-4-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['কোনো', 'লোক', 'নৌকা', 'কৌতূহল', 'পৌর', 'যৌবন', 'গৌরব', 'ভোর', 'দোকান'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-2-4-3',
                type: 'mastery',
                title: 'ও ও ঔ কার মাস্টারি',
                items: ['নৌকা', 'কৌতূহল', 'গৌরব', 'কোনো', 'লোক', 'দোকান', 'পৌর'],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
      {
        id: 'mod-2-2',
        level: 2,
        title: 'Stage B: কার Mixed ও কার+যুক্তাক্ষর',
        description: 'কার সমন্বয়, কার+যুক্তাক্ষর ও ব্যাপক কার-চিহ্ন রিভিউ',
        lessons: [
          {
            id: 'lesson-2-5',
            title: 'কার সমন্বিত মিশ্র অনুশীলন (Mixed Kar)',
            subtitle: 'কা কি কী, কু কূ কৃ, কে কৈ, কো কৌ, কা গি রু সে মো',
            level: 2,
            moduleId: 'mod-2-2',
            moduleTitle: 'Stage B: কার Mixed ও কার+যুক্তাক্ষর',
            description: 'একই ব্যঞ্জনে সব কারের আবর্তন এবং বিভিন্ন কারের দ্রুত সুইচিং।',
            skills: ['kar-mixed-rotation'],
            prerequisites: ['lesson-2-4'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-2-5-1',
                type: 'pattern',
                title: 'কার রোটেশন ড্রিল',
                items: [
                  'কা কি কী', 'কু কূ কৃ', 'কে কৈ', 'কো কৌ',
                  'গা গি গী', 'গু গূ গৃ', 'গে গৈ', 'গো গৌ',
                  'কা গি রু সে মো'
                ],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-2-5-2',
                type: 'mastery',
                title: 'কার রোটেশন মাস্টারি',
                items: ['কা গি রু সে মো', 'কু কূ কৃ', 'কে কৈ', 'কো কৌ', 'গে গৈ', 'গো গৌ'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-2-6',
            title: 'কার + যুক্তাক্ষর কম্বিনেশন (Kar + Conjuncts)',
            subtitle: 'ক্রি, গ্রা, প্রে, ত্রু, শ্রে, দ্রু, প্রী',
            level: 2,
            moduleId: 'mod-2-2',
            moduleTitle: 'Stage B: কার Mixed ও কার+যুক্তাক্ষর',
            description: 'যুক্তাক্ষরের সাথে কারের সঠিক সিকোয়েন্স (ব্যঞ্জন+্+ব্যঞ্জন+কার)।',
            skills: ['kar-conjunct-combo'],
            prerequisites: ['lesson-2-5'],
            estimatedMinutes: 5,
            difficulty: 5,
            sections: [
              {
                id: 'sec-2-6-1',
                type: 'pattern',
                title: 'কার+যুক্তাক্ষর প্যাটার্ন',
                items: ['ক্রি', 'গ্রা', 'প্রে', 'ত্রু', 'শ্রে', 'দ্রু', 'প্রী', 'ক্লি', 'গ্লো', 'প্লু'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-2-6-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['ক্রিকেট', 'গ্রাম', 'প্রেম', 'ছাত্রী', 'শ্রেণী', 'দ্রুত', 'প্রীতি', 'ক্লাস'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-2-6-3',
                type: 'mastery',
                title: 'কার+যুক্তাক্ষর মাস্টারি',
                items: ['ক্রিকেট', 'গ্রাম', 'প্রেম', 'ছাত্রী', 'শ্রেণী', 'দ্রুত', 'ক্লাস'],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 3: হসন্ত কোর্স (HASANTA DEEP DIVE) ───────────────────────────
  {
    level: 3,
    title: 'হসন্ত ও ব্যঞ্জন সন্ধি কোর্স (Hasanta Course)',
    tagline: 'HAS-01 থেকে HAS-05 পর্যন্ত হসন্ত ও দ্বিত্ব রূপের নিবিড় শিক্ষা',
    description: 'হসন্তের একক ট্রানজিশন, ক্ক-ক্ত-ন্ত-ন্দ সন্ধি এবং স্ট-স্থ-স্ক-স্প ও বিরল হসন্তের পরিপূর্ণ কোর্স।',
    badge: '⚡',
    modules: [
      {
        id: 'mod-3-1',
        level: 3,
        title: 'হসন্ত ও দ্বিত্ব রূপ (HAS-01 to HAS-05)',
        description: 'হসন্ত ট্রানজিশন, স্পর্শ ব্যঞ্জন ও শ/ষ/স এর যুক্ত রূপ',
        lessons: [
          {
            id: 'lesson-3-1',
            title: 'HAS-01: একক হসন্ত ট্রানজিশন (ক্, ত্, ন্, স্)',
            subtitle: 'h কি দিয়ে ব্যঞ্জনের অর্ধরূপ তৈরি',
            level: 3,
            moduleId: 'mod-3-1',
            moduleTitle: 'হসন্ত ও দ্বিত্ব রূপ',
            description: 'হসন্ত (h) ব্যবহারের মেকানিক্স ও আঙুলের ট্রানজিশন।',
            skills: ['hasanta-01'],
            prerequisites: ['lesson-2-6'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-3-1-1',
                type: 'pattern',
                title: 'একক হসন্ত প্যাটার্ন',
                items: ['ক্', 'ত্', 'ন্', 'স্', 'ব্', 'দ্', 'প্', 'ম্', 'র্'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-3-1-2',
                type: 'mastery',
                title: 'HAS-01 মাস্টারি',
                items: ['ক্', 'ত্', 'ন্', 'স্', 'ব্', 'দ্'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-3-2',
            title: 'HAS-02: দ্বিত্ব ও সন্ধি (ক্ক, ক্ত, ন্ত, ন্দ)',
            subtitle: 'পাক্কা, রক্ত, শান্ত, আনন্দ ইত্যাদি শব্দ',
            level: 3,
            moduleId: 'mod-3-1',
            moduleTitle: 'হসন্ত ও দ্বিত্ব রূপ',
            description: 'ক+্+ক=ক্ক, ক+্+ত=ক্ত, ন+্+ত=ন্ত, ন+্+দ=ন্দ এর সঠিক টাইপিং।',
            skills: ['hasanta-02'],
            prerequisites: ['lesson-3-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-3-2-1',
                type: 'pattern',
                title: 'দ্বিত্ব প্যাটার্ন ড্রিল',
                items: ['ক্ক', 'ক্ত', 'ন্ত', 'ন্দ', 'পাক্কা', 'রক্ত', 'শান্ত', 'আনন্দ'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-3-2-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['পাক্কা', 'রক্ত', 'শান্ত', 'আনন্দ', 'মুক্তি', 'সুন্দর', 'অনন্ত', 'বন্ধন'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-3-2-3',
                type: 'mastery',
                title: 'HAS-02 মাস্টারি',
                items: ['পাক্কা', 'রক্ত', 'শান্ত', 'আনন্দ', 'মুক্তি', 'সুন্দর'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-3-3',
            title: 'HAS-03: দন্ত্য-স যুক্ত রূপ (স্ট, স্থ, স্ক, স্প)',
            subtitle: 'স্টেশন, স্থান, স্কুল, স্পর্শ ইত্যাদি শব্দ',
            level: 3,
            moduleId: 'mod-3-1',
            moduleTitle: 'হসন্ত ও দ্বিত্ব রূপ',
            description: 'স+্+ট=স্ট, স+্+থ=স্থ, স+্+ক=স্ক, স+্+প=স্প।',
            skills: ['hasanta-03'],
            prerequisites: ['lesson-3-2'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-3-3-1',
                type: 'pattern',
                title: 'দন্ত্য-স যুক্ত প্যাটার্ন',
                items: ['স্ট', 'স্থ', 'স্ক', 'স্প', 'স্টেশন', 'স্থান', 'স্কুল', 'স্পর্শ'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-3-3-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['স্টেশন', 'স্থান', 'স্কুল', 'স্পর্শ', 'স্পষ্ট', 'স্বাস্থ্য', 'অস্থির', 'পুস্তক'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-3-3-3',
                type: 'mastery',
                title: 'HAS-03 মাস্টারি',
                items: ['স্টেশন', 'স্থান', 'স্কুল', 'স্পর্শ', 'স্পষ্ট', 'স্বাস্থ্য'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-3-4',
            title: 'HAS-04: মূর্ধন্য-ষ ও তালব্য-শ যুক্ত রূপ (ষ্ট, ষ্ঠ, শ্চ, ঞ্চ)',
            subtitle: 'কষ্ট, শ্রেষ্ঠ, নিশ্চয়, মঞ্চ ইত্যাদি শব্দ',
            level: 3,
            moduleId: 'mod-3-1',
            moduleTitle: 'হসন্ত ও দ্বিত্ব রূপ',
            description: 'ষ+্+ট=ষ্ট, ষ+্+ঠ=ষ্ঠ, শ+্+চ=শ্চ, ঞ+্+চ=ঞ্চ।',
            skills: ['hasanta-04'],
            prerequisites: ['lesson-3-3'],
            estimatedMinutes: 5,
            difficulty: 5,
            sections: [
              {
                id: 'sec-3-4-1',
                type: 'pattern',
                title: 'ষ ও শ যুক্ত প্যাটার্ন',
                items: ['ষ্ট', 'ষ্ঠ', 'শ্চ', 'ঞ্চ', 'কষ্ট', 'শ্রেষ্ঠ', 'নিশ্চয়', 'মঞ্চ'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-3-4-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['কষ্ট', 'শ্রেষ্ঠ', 'নিশ্চয়', 'মঞ্চ', 'বৃষ্টি', 'প্রতিষ্ঠা', 'আশ্চর্য', 'অঞ্চল'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-3-4-3',
                type: 'mastery',
                title: 'HAS-04 মাস্টারি',
                items: ['কষ্ট', 'শ্রেষ্ঠ', 'নিশ্চয়', 'মঞ্চ', 'বৃষ্টি', 'প্রতিষ্ঠা'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-3-5',
            title: 'HAS-05: হসন্ত মাস্টার পরীক্ষা ও বিরল সন্ধি',
            subtitle: 'হসন্ত কোর্সের পূর্ণাঙ্গ মূল্যায়ন (৯৫%+ আবশ্যক)',
            level: 3,
            moduleId: 'mod-3-1',
            moduleTitle: 'হসন্ত ও দ্বিত্ব রূপ',
            description: 'হসন্তের সকল কম্বিনেশন ও জটিল যুক্তাক্ষরের মাস্টার পরীক্ষা।',
            skills: ['hasanta-final-mastery'],
            prerequisites: ['lesson-3-4'],
            estimatedMinutes: 5,
            difficulty: 5,
            sections: [
              {
                id: 'sec-3-5-1',
                type: 'mastery',
                title: 'হসন্ত মাস্টার টেস্ট',
                items: [
                  'রক্ত', 'আনন্দ', 'স্কুল', 'স্টেশন', 'শ্রেষ্ঠ', 'কষ্ট', 'নিশ্চয়', 'স্বাস্থ্য', 'বৃষ্টি'
                ],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 4: ফলা পরিবার (PHOLA FAMILIES) ──────────────────────────────
  {
    level: 4,
    title: 'ফলা পরিবার ও যুক্তাক্ষর (Phola Families)',
    tagline: 'র-ফলা, য-ফলা, ল-ফলা, রেফ, ব-ফলা ও ম-ফলা পরিবার',
    description: 'বাংলা ভাষার প্রতিটি ফলা পরিবারের সুনির্দিষ্ট বিন্যাস ও সঠিক টাইপিং মেকানিক্স।',
    badge: '🌿',
    modules: [
      {
        id: 'mod-4-1',
        level: 4,
        title: 'ফলা পরিবারভিত্তিক পাঠ',
        description: 'র-ফলা, য-ফলা, ল-ফলা, রেফ, ব/ম-ফলা',
        lessons: [
          {
            id: 'lesson-4-1',
            title: 'র-ফলা পরিবার (ক্র, গ্র, প্র, ব্র, ত্র, দ্র)',
            subtitle: 'গ্রাম, প্রথম, ব্রত, ছাত্র, দ্রুত ইত্যাদি শব্দ',
            level: 4,
            moduleId: 'mod-4-1',
            moduleTitle: 'ফলা পরিবারভিত্তিক পাঠ',
            description: 'ব্যঞ্জন + হসন্ত + র = র-ফলা।',
            skills: ['phola-ra'],
            prerequisites: ['lesson-3-5'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-4-1-1',
                type: 'pattern',
                title: 'র-ফলা প্যাটার্ন',
                items: ['ক্র', 'গ্র', 'প্র', 'ব্র', 'ত্র', 'দ্র', 'শ্র', 'ভ্র'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-4-1-2',
                type: 'word',
                title: 'র-ফলা শব্দ ড্রিল',
                items: ['গ্রাম', 'প্রথম', 'ব্রত', 'ছাত্র', 'দ্রুত', 'শ্রম', 'ভ্রমণ', 'ক্রিকেট', 'প্রকৃতি'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-4-1-3',
                type: 'mastery',
                title: 'র-ফলা মাস্টারি',
                items: ['গ্রাম', 'প্রথম', 'ছাত্র', 'প্রকৃতি', 'দ্রুত', 'শ্রম', 'ভ্রমণ'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-4-2',
            title: 'য-ফলা পরিবার (ক্য, ব্য, গ্য, দ্য, ন্য)',
            subtitle: 'বাক্য, ব্যয়, ব্যবসা, ধন্য, পদ্য ইত্যাদি শব্দ',
            level: 4,
            moduleId: 'mod-4-1',
            moduleTitle: 'ফলা পরিবারভিত্তিক পাঠ',
            description: 'ব্যঞ্জন + ্য (z কি) অথবা ব্যঞ্জন + হসন্ত + য = য-ফলা।',
            skills: ['phola-ja'],
            prerequisites: ['lesson-4-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-4-2-1',
                type: 'pattern',
                title: 'য-ফলা প্যাটার্ন',
                items: ['ক্য', 'ব্য', 'গ্য', 'দ্য', 'ন্য', 'প্য', 'ম্য', 'ল্য'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-4-2-2',
                type: 'word',
                title: 'য-ফলা শব্দ ড্রিল',
                items: ['বাক্য', 'ব্যয়', 'ব্যবসা', 'ধন্য', 'পদ্য', 'গদ্য', 'মূল্য', 'সত্য', 'বিদ্যা'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-4-2-3',
                type: 'mastery',
                title: 'য-ফলা মাস্টারি',
                items: ['বাক্য', 'ব্যবসা', 'ধন্য', 'সত্য', 'বিদ্যা', 'মূল্য', 'ব্যয়'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-4-3',
            title: 'ল-ফলা ও রেফ পরিবার (ক্ল, গ্ল, প্ল, র্ক, র্গ, র্ম)',
            subtitle: 'ক্লাস, বিপ্লব, কর্ম, ধর্ম, গর্ব, সূর্য ইত্যাদি শব্দ',
            level: 4,
            moduleId: 'mod-4-1',
            moduleTitle: 'ফলা পরিবারভিত্তিক পাঠ',
            description: 'ল-ফলা এবং র+্+ব্যঞ্জন = রেফ এর টাইপিং কৌশল।',
            skills: ['phola-la-ref'],
            prerequisites: ['lesson-4-2'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-4-3-1',
                type: 'pattern',
                title: 'ল-ফলা ও রেফ প্যাটার্ন',
                items: ['ক্ল', 'গ্ল', 'প্ল', 'ব্ল', 'র্ক', 'র্গ', 'র্ত', 'র্দ', 'র্ম', 'র্ষ'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-4-3-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['ক্লাস', 'গ্লানি', 'বিপ্লব', 'কর্ম', 'ধর্ম', 'গর্ব', 'সূর্য', 'তর্ক', 'বর্ষা'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-4-3-3',
                type: 'mastery',
                title: 'ল-ফলা ও রেফ মাস্টারি',
                items: ['ক্লাস', 'বিপ্লব', 'কর্ম', 'ধর্ম', 'গর্ব', 'সূর্য', 'বর্ষা'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-4-4',
            title: 'ব-ফলা ও ম-ফলা পরিবার (দ্ব, শ্ব, স্ব, পদ্ম, গ্রীষ্ম)',
            subtitle: 'দ্বিধা, বিশ্ব, স্বাধীনতা, পদ্ম, গ্রীষ্ম, বিস্ময়',
            level: 4,
            moduleId: 'mod-4-1',
            moduleTitle: 'ফলা পরিবারভিত্তিক পাঠ',
            description: 'ব-ফলা ও ম-ফলা যুক্ত অক্ষরের নিয়ম ও শব্দভাণ্ডার।',
            skills: ['phola-ba-ma'],
            prerequisites: ['lesson-4-3'],
            estimatedMinutes: 5,
            difficulty: 5,
            sections: [
              {
                id: 'sec-4-4-1',
                type: 'pattern',
                title: 'ব ও ম ফলা প্যাটার্ন',
                items: ['দ্ব', 'শ্ব', 'স্ব', 'দ্ম', 'ষ্ম', 'ত্ম', 'স্ম'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-4-4-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['দ্বিধা', 'বিশ্ব', 'স্বাধীনতা', 'স্বদেশ', 'পদ্ম', 'গ্রীষ্ম', 'বিস্ময়', 'আত্মা'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-4-4-3',
                type: 'mastery',
                title: 'ফলা চূড়ান্ত মাস্টারি পরীক্ষা',
                items: ['স্বাধীনতা', 'বিশ্ব', 'গ্রীষ্ম', 'বিস্ময়', 'গ্রাম', 'ব্যবসা', 'কর্ম', 'বিপ্লব'],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 5: যুক্তাক্ষর কাঠিন্য স্তর (TIERED CONJUNCTS) ─────────────────
  {
    level: 5,
    title: 'যুক্তাক্ষর কাঠিন্য স্তর (Tiered Conjuncts)',
    tagline: 'সহজ, মাঝারি, কঠিন ও অতি-কঠিন ত্রি-ব্যঞ্জন যুক্তাক্ষর',
    description: 'ক্ত, ন্ত থেকে ক্ষ, জ্ঞ, হ্ম এবং ক্ষ্ম, ষ্ক্র, ন্ত্র পর্যন্ত প্রতিটি স্তরের জয়।',
    badge: '🔥',
    modules: [
      {
        id: 'mod-5-1',
        level: 5,
        title: 'কাঠিন্যভিত্তিক যুক্তাক্ষর (Tiers 1 to 4)',
        description: 'সহজ থেকে জটিলতম ত্রি-ব্যঞ্জন যুক্তবর্ণ',
        lessons: [
          {
            id: 'lesson-5-1',
            title: 'সহজ ও মাঝারি যুক্তাক্ষর (Tier 1 & 2)',
            subtitle: 'ক্ত, ন্ত, ন্দ, ত্র, ক্র, গ্র, প্র, দ্র',
            level: 5,
            moduleId: 'mod-5-1',
            moduleTitle: 'কাঠিন্যভিত্তিক যুক্তাক্ষর',
            description: 'বহুল ব্যবহৃত সাধারণ ও মাঝারি যুক্তাক্ষরের গতিশীল ড্রিল।',
            skills: ['conjunct-tier-1-2'],
            prerequisites: ['lesson-4-4'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-5-1-1',
                type: 'word',
                title: 'সহজ ও মাঝারি শব্দ ড্রিল',
                items: ['রক্ত', 'শান্ত', 'আনন্দ', 'বন্ধু', 'প্রথম', 'ছাত্র', 'দ্রুত', 'গ্রাম'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-5-1-2',
                type: 'mastery',
                title: 'Tier 1 & 2 মাস্টারি',
                items: ['রক্ত', 'আনন্দ', 'বন্ধু', 'প্রথম', 'ছাত্র', 'দ্রুত'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-5-2',
            title: 'কঠিন যুক্তাক্ষর (Tier 3: ক্ষ, জ্ঞ, শ্র, হ্ম, চ্ছ, ষ্ক, ষ্ঠ)',
            subtitle: 'শিক্ষা, পরীক্ষা, জ্ঞান, বিজ্ঞান, ব্রাহ্মণ, ইচ্ছা',
            level: 5,
            moduleId: 'mod-5-1',
            moduleTitle: 'কাঠিন্যভিত্তিক যুক্তাক্ষর',
            description: 'বাংলা ভাষার অন্যতম গুরুত্বপূর্ণ ও চ্যালেঞ্জিং যুক্তবর্ণ।',
            skills: ['conjunct-tier-3'],
            prerequisites: ['lesson-5-1'],
            estimatedMinutes: 6,
            difficulty: 6,
            sections: [
              {
                id: 'sec-5-2-1',
                type: 'pattern',
                title: 'কঠিন যুক্তবর্ণ প্যাটার্ন',
                items: ['ক্ষ', 'জ্ঞ', 'হ্ম', 'চ্ছ', 'ষ্ক', 'ষ্ঠ', 'শ্র', 'ব্ধ'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-5-2-2',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['শিক্ষা', 'পরীক্ষা', 'জ্ঞান', 'বিজ্ঞান', 'ব্রাহ্মণ', 'ইচ্ছা', 'শ্রেষ্ঠ', 'শ্রদ্ধা'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-5-2-3',
                type: 'mastery',
                title: 'Tier 3 মাস্টারি',
                items: ['শিক্ষা', 'পরীক্ষা', 'জ্ঞান', 'বিজ্ঞান', 'ব্রাহ্মণ', 'শ্রেষ্ঠ'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-5-3',
            title: 'খুব কঠিন ত্রি-ব্যঞ্জন যুক্তাক্ষর (Tier 4: ক্ষ্ম, ষ্ক্র, ন্ত্র, ম্প্র, ষ্ট্র)',
            subtitle: 'সূক্ষ্ম, নিষ্ক্রিয়, যন্ত্র, সম্প্রদায়, রাষ্ট্র',
            level: 5,
            moduleId: 'mod-5-1',
            moduleTitle: 'কাঠিন্যভিত্তিক যুক্তাক্ষর',
            description: 'তিনটি ব্যঞ্জন দিয়ে গঠিত সবচেয়ে জটিল যুক্তাক্ষরের সঠিক টাইপিং।',
            skills: ['conjunct-tier-4'],
            prerequisites: ['lesson-5-2'],
            estimatedMinutes: 6,
            difficulty: 7,
            sections: [
              {
                id: 'sec-5-3-1',
                type: 'pattern',
                title: 'ত্রি-ব্যঞ্জন প্যাটার্ন',
                items: ['ক্ষ্ম', 'ষ্ক্র', 'ন্ত্র', 'ম্প্র', 'ষ্ট্র', 'চ্ছ্ব', 'স্ক্র'],
                requiredAccuracy: 93,
              },
              {
                id: 'sec-5-3-2',
                type: 'word',
                title: 'জটিল শব্দ ড্রিল',
                items: ['সূক্ষ্ম', 'নিষ্ক্রিয়', 'যন্ত্র', 'সম্প্রদায়', 'রাষ্ট্র', 'অস্ট্রেলিয়া', 'উচ্ছ্বাস'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-5-3-3',
                type: 'mastery',
                title: 'যুক্তাক্ষর ফাইনাল মাস্টারি',
                items: ['সূক্ষ্ম', 'যন্ত্র', 'রাষ্ট্র', 'বিজ্ঞান', 'পরীক্ষা', 'সম্প্রদায়', 'স্বাস্থ্য'],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 6: বিশেষ বাংলা বর্ণ ও চিহ্ন (SPECIAL CHARACTERS) ──────────────
  {
    level: 6,
    title: 'বিশেষ বাংলা বর্ণ ও চিহ্ন (Special Characters)',
    tagline: 'ঁ, ং, ঃ, ়, ৎ, ড়, ঢ়, য় এর যথাযথ প্রয়োগ',
    description: 'চন্দ্রবিন্দু, অনুস্বার, বিসর্গ, নুকতা, খণ্ড-ত এবং ড-ঢ়-য় এর নির্ভুল ব্যবহার।',
    badge: '✨',
    modules: [
      {
        id: 'mod-6-1',
        level: 6,
        title: 'নাসিক্য ও বিশেষ বর্ণমালা',
        description: 'চিহ্ন ও বিশেষ বর্ণের শব্দভাণ্ডার',
        lessons: [
          {
            id: 'lesson-6-1',
            title: 'চন্দ্রবিন্দু, অনুস্বার, বিসর্গ, খণ্ড-ত ও নুকতা',
            subtitle: 'ঁ, ং, ঃ, ৎ, ় (চাঁদ, রং, দুঃখ, হঠাৎ, বাড়ি)',
            level: 6,
            moduleId: 'mod-6-1',
            moduleTitle: 'নাসিক্য ও বিশেষ বর্ণমালা',
            description: 'ঁ (Shift+Q), ং (Shift+Z), ঃ (Shift+W), ৎ (Shift+F), ় (-) এর নিয়ম।',
            skills: ['special-signs'],
            prerequisites: ['lesson-5-3'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-6-1-1',
                type: 'word',
                title: 'বিশেষ চিহ্নযুক্ত শব্দ',
                items: ['চাঁদ', 'হাঁস', 'রংধনু', 'সিংহ', 'দুঃখ', 'উৎসব', 'হঠাৎ', 'বিদ্যুৎ', 'বাংলা'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-6-1-2',
                type: 'mastery',
                title: 'বিশেষ চিহ্ন মাস্টারি',
                items: ['চাঁদ', 'সিংহ', 'দুঃখ', 'উৎসব', 'বিদ্যুৎ', 'বাংলা', 'হঠাৎ'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-6-2',
            title: 'ড়, ঢ়, য় ও ঞ বিশেষ বর্ণমালা',
            subtitle: 'পাহাড়, আষাঢ়, সময়, মিয়া ইত্যাদি শব্দ',
            level: 6,
            moduleId: 'mod-6-1',
            moduleTitle: 'নাসিক্য ও বিশেষ বর্ণমালা',
            description: 'ড় (Shift+R), ঢ় (Shift+P), য় (Shift+Y), ঞ (Shift+\\) এর নিখুঁত টাইপিং।',
            skills: ['special-letters'],
            prerequisites: ['lesson-6-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-6-2-1',
                type: 'word',
                title: 'শব্দ ড্রিল',
                items: ['পাহাড়', 'বাড়ি', 'আষাঢ়', 'গাঢ়', 'সময়', 'ভয়', 'মিঞা', 'দাঁড়কাক', 'ঘড়ি'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-6-2-2',
                type: 'mastery',
                title: 'বিশেষ বর্ণ মাস্টারি',
                items: ['পাহাড়', 'আষাঢ়', 'সময়', 'বাড়ি', 'গাঢ়', 'দাঁড়কাক'],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 7: বাংলা সংখ্যা ও আর্থিক ফরম্যাট (NUMERALS & FORMATS) ─────────
  {
    level: 7,
    title: 'বাংলা সংখ্যা ও আর্থিক ফরম্যাট (Bengali Numerals)',
    tagline: '০ ১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯, তারিখ, মুদ্রা (৳) ও শতাংশ (%)',
    description: 'দৈনন্দিন ও অফিসিয়াল কাজে বাংলা সংখ্যার দ্রুত ও নির্ভুল টাইপিং।',
    badge: '🔢',
    modules: [
      {
        id: 'mod-7-1',
        level: 7,
        title: 'সংখ্যা ও বাণিজ্যিক ফরম্যাট',
        description: 'সংখ্যা ০-৯, তারিখ, সময় ও মুদ্রা',
        lessons: [
          {
            id: 'lesson-7-1',
            title: 'বাংলা সংখ্যা ০ থেকে ৯',
            subtitle: '০ ১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯ ও সাধারণ ডিজিট',
            level: 7,
            moduleId: 'mod-7-1',
            moduleTitle: 'সংখ্যা ও বাণিজ্যিক ফরম্যাট',
            description: 'টপ নাম্বার রো-তে বাংলা সংখ্যা টাইপ করার অভ্যাস।',
            skills: ['numerals-basic'],
            prerequisites: ['lesson-6-2'],
            estimatedMinutes: 4,
            difficulty: 3,
            sections: [
              {
                id: 'sec-7-1-1',
                type: 'pattern',
                title: 'সংখ্যা প্যাটার্ন ড্রিল',
                items: ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯', '১০', '২০', '৫০', '১০০'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-7-1-2',
                type: 'mastery',
                title: 'সংখ্যা বেসিক মাস্টারি',
                items: ['১২৩৪৫', '৬৭৮৯০', '১৯৭১', '২০২৬', '৫০০', '১০০০'],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-7-2',
            title: 'বাস্তব সংখ্যা ফরম্যাট: তারিখ, টাকা ও শতাংশ',
            subtitle: '২০২৬, ১৩ নভেম্বর ২০০০, ৳ ১০০, ২৫%, ১২:৩০',
            level: 7,
            moduleId: 'mod-7-1',
            moduleTitle: 'সংখ্যা ও বাণিজ্যিক ফরম্যাট',
            description: 'বাস্তব জীবনের হিসাব, তারিখ, সময় ও কারেন্সি ফরম্যাট।',
            skills: ['numerals-advanced-formats'],
            prerequisites: ['lesson-7-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-7-2-1',
                type: 'word',
                title: 'বাস্তব সংখ্যা ফরম্যাট ড্রিল',
                items: ['২০২৬ সাল', '১৩ নভেম্বর ২০০০', '৳ ৫০০', '৳ ১০০০', '২৫%', '৫০%', '১২:৩০ মিনিট'],
                requiredAccuracy: 94,
              },
              {
                id: 'sec-7-2-2',
                type: 'mastery',
                title: 'সংখ্যা ও ফরম্যাট ফাইনাল মাস্টারি',
                items: ['২০২৬ সাল', '৳ ৫০০', '২৫%', '১২:৩০ মিনিট', '১৩ নভেম্বর ২০০০', '৳ ১০০০'],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 8: যতিচিহ্ন ও বিরামচিহ্ন (PUNCTUATION COURSE) ───────────────────
  {
    level: 8,
    title: 'যতিচিহ্ন ও বিরামচিহ্ন (Punctuation Course)',
    tagline: 'দাঁড়ি (।), কমা (,), প্রশ্নবোধক (?), বিস্ময় (!), উদ্ধৃতি ও কোলন',
    description: 'পূর্ণাঙ্গ বাক্য গঠনে প্রয়োজনীয় সকল বাংলা বিরামচিহ্নের নির্ভুল ব্যবহার।',
    badge: '🔣',
    modules: [
      {
        id: 'mod-8-1',
        level: 8,
        title: 'বিরামচিহ্ন ও উদ্ধৃতি',
        description: 'দাঁড়ি, কমা, হাইফেন, ড্যাশ ও ব্র্যাকেট',
        lessons: [
          {
            id: 'lesson-8-1',
            title: 'দাঁড়ি, কমা, প্রশ্নবোধক ও বিস্ময়চিহ্ন',
            subtitle: '।, ,, ?, ! এর নিয়ম ও দ্রুত ব্যবহার',
            level: 8,
            moduleId: 'mod-8-1',
            moduleTitle: 'বিরামচিহ্ন ও উদ্ধৃতি',
            description: 'দাঁড়ি (Period / .) এবং অন্যান্য চিহ্নের সাবলীল টাইপিং।',
            skills: ['punctuation-basic'],
            prerequisites: ['lesson-7-2'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-8-1-1',
                type: 'pattern',
                title: 'যতিচিহ্ন প্যাটার্ন',
                items: ['।', ',', '?', '!', '।', ',', '?', '!'],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-8-1-2',
                type: 'word',
                title: 'চিহ্নযুক্ত বাক্য ড্রিল',
                items: [
                  'আমার দেশ বাংলাদেশ।',
                  'তুমি কি যাবে?',
                  'সাবাশ, আমরা পেরেছি!',
                  'দাঁড়াও, আমি আসছি।',
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-8-1-3',
                type: 'mastery',
                title: 'বিরামচিহ্ন মাস্টারি',
                items: [
                  'আমার দেশ বাংলাদেশ।',
                  'তুমি কি যাবে?',
                  'সাবাশ, আমরা পেরেছি!',
                  'দাঁড়াও, আমি আসছি।',
                ],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-8-2',
            title: 'কোলন, সেমিকোলন, ড্যাশ ও উদ্ধৃতিচিহ্ন',
            subtitle: ':, ;, —, -, (, ), ", \' এর ব্যবহার',
            level: 8,
            moduleId: 'mod-8-1',
            moduleTitle: 'বিরামচিহ্ন ও উদ্ধৃতি',
            description: 'উদ্ধৃতি ও জটিল বিরামচিহ্ন সহযোগে প্রফেশনাল ড্রাফট।',
            skills: ['punctuation-advanced'],
            prerequisites: ['lesson-8-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-8-2-1',
                type: 'word',
                title: 'উদ্ধৃতি ও জটিল চিহ্ন ড্রিল',
                items: [
                  'শিক্ষক বললেন, "সততা সর্বোৎকৃষ্ট পন্থা।"',
                  'বিষয়: ছুটির আবেদন।',
                  'নজরুল (১৮৯৯-১৯৭৬) আমাদের জাতীয় কবি।',
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-8-2-2',
                type: 'mastery',
                title: 'পূর্ণাঙ্গ যতিচিহ্ন মাস্টারি',
                items: [
                  'শিক্ষক বললেন, "সততা সর্বোৎকৃষ্ট পন্থা।"',
                  'বিষয়: ছুটির আবেদন।',
                  'নজরুল (১৮৯৯-১৯৭৬) আমাদের জাতীয় কবি।',
                ],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 9: বহুল ব্যবহৃত শব্দ ও শব্দগুচ্ছ (WORDS & PHRASES) ───────────
  {
    level: 9,
    title: 'বহুল ব্যবহৃত বাংলা শব্দ ও শব্দগুচ্ছ (Words & Phrases)',
    tagline: 'হাই-ফ্রিকোয়েন্সি শব্দ, বিষয়ভিত্তিক শব্দভাণ্ডার ও বাক্যগুচ্ছ',
    description: 'বাস্তব জীবনে সর্বাধিক ব্যবহৃত বাংলা শব্দ এবং স্পেস ট্রানজিশনের মসৃণ প্রবাহ।',
    badge: '📚',
    modules: [
      {
        id: 'mod-9-1',
        level: 9,
        title: 'শীর্ষ বাংলা শব্দ ও শব্দগুচ্ছ',
        description: 'হাই ফ্রিকোয়েন্সি শব্দ, ২/৩/৪ অক্ষরের শব্দ ও ফ্রেজ',
        lessons: [
          {
            id: 'lesson-9-1',
            title: 'শীর্ষ ৩০ বহুল ব্যবহৃত বাংলা শব্দ',
            subtitle: 'আমি, আমরা, তুমি, আপনি, সে, এটা, ওটা, করে, হয়, আছে...',
            level: 9,
            moduleId: 'mod-9-1',
            moduleTitle: 'শীর্ষ বাংলা শব্দ ও শব্দগুচ্ছ',
            description: 'বাংলা ভাষার মূল ভিত্তি এবং সর্বাধিক ব্যবহৃত শীর্ষ শব্দাবলি।',
            skills: ['high-frequency-words'],
            prerequisites: ['lesson-8-2'],
            estimatedMinutes: 5,
            difficulty: 3,
            sections: [
              {
                id: 'sec-9-1-1',
                type: 'word',
                title: 'কমন শব্দ ড্রিল',
                items: [
                  'আমি', 'আমরা', 'তুমি', 'আপনি', 'সে', 'এটা', 'ওটা', 'করে',
                  'হয়', 'আছে', 'নিয়ে', 'থেকে', 'জন্য', 'করা', 'হবে', 'ছিল'
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-9-1-2',
                type: 'mastery',
                title: 'কমন শব্দ মাস্টারি',
                items: [
                  'আমি', 'আমরা', 'তুমি', 'আপনি', 'সে', 'এটা', 'হয়', 'আছে', 'জন্য', 'করা'
                ],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-9-2',
            title: 'বিষয়ভিত্তিক শব্দভাণ্ডার (দৈনন্দিন, শিক্ষা, প্রযুক্তি, অফিস)',
            subtitle: 'কম্পিউটার, ইন্টারনেট, অফিস, আদালত, ব্যবসা, সংবাদ',
            level: 9,
            moduleId: 'mod-9-1',
            moduleTitle: 'শীর্ষ বাংলা শব্দ ও শব্দগুচ্ছ',
            description: 'কর্মক্ষেত্র ও পড়াশোনার জন্য অপরিহার্য পরিভাষা।',
            skills: ['thematic-vocabulary'],
            prerequisites: ['lesson-9-1'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-9-2-1',
                type: 'word',
                title: 'বিষয়ভিত্তিক শব্দ ড্রিল',
                items: [
                  'কম্পিউটার', 'প্রযুক্তি', 'বিদ্যালয়', 'শিক্ষা', 'ব্যবসা',
                  'অফিস', 'আদালত', 'সংবাদ', 'সরকার', 'ডিজিটাল', 'কর্মকর্তা'
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-9-2-2',
                type: 'mastery',
                title: 'বিষয়ভিত্তিক শব্দ মাস্টারি',
                items: [
                  'কম্পিউটার', 'প্রযুক্তি', 'বিদ্যালয়', 'ব্যবসা', 'ডিজিটাল', 'কর্মকর্তা'
                ],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-9-3',
            title: 'শব্দগুচ্ছ ও স্পেস ট্রানজিশন (Phrase Lessons)',
            subtitle: 'আমি যাব, তুমি কি আসবে, কেমন আছো, আজ খুব ভালো দিন',
            level: 9,
            moduleId: 'mod-9-1',
            moduleTitle: 'শীর্ষ বাংলা শব্দ ও শব্দগুচ্ছ',
            description: 'শব্দ থেকে শব্দে স্পেস চেপে দ্রুত ট্রানজিশন নেওয়ার দক্ষতা।',
            skills: ['phrase-transition'],
            prerequisites: ['lesson-9-2'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-9-3-1',
                type: 'word',
                title: 'ফ্রেজ ড্রিল',
                items: [
                  'আমি যাব',
                  'তুমি কি আসবে',
                  'কেমন আছো',
                  'আজ খুব ভালো দিন',
                  'আমরা সবাই যাব',
                  'সবাই মিলে কাজ করব',
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-9-3-2',
                type: 'mastery',
                title: 'ফ্রেজ ফাইনাল মাস্টারি',
                items: [
                  'আমি যাব',
                  'তুমি কি আসবে',
                  'কেমন আছো',
                  'আজ খুব ভালো দিন',
                  'আমরা সবাই যাব',
                ],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 10: বাক্য ক্রমবিকাশ (SENTENCE PROGRESSION) ───────────────────
  {
    level: 10,
    title: 'বাক্য ক্রমবিকাশ (Sentence Progression)',
    tagline: 'ছোট সরল বাক্য থেকে মাঝারি, দীর্ঘ ও জটিল বাক্য গঠন',
    description: 'Sentence 1 (সরল) থেকে Sentence 4 (জটিল যুক্তাক্ষর ও যতিচিহ্ন) পর্যন্ত পূর্ণ প্রস্তুতি।',
    badge: '📝',
    modules: [
      {
        id: 'mod-10-1',
        level: 10,
        title: 'বাক্যের কাঠিন্য স্তর (Sentences 1 to 4)',
        description: 'সরল, যৌগিক, দীর্ঘ ও জটিল বাক্য প্রবাহ',
        lessons: [
          {
            id: 'lesson-10-1',
            title: 'Sentence 1 & 2: সরল ও মাঝারি বাক্য',
            subtitle: 'আমি যাই। → আমি আজ বাজারে যাই।',
            level: 10,
            moduleId: 'mod-10-1',
            moduleTitle: 'বাক্যের কাঠিন্য স্তর',
            description: 'ছোট সরল বাক্য দিয়ে টাইপিং রিদম তৈরি করা।',
            skills: ['sentence-stage-1-2'],
            prerequisites: ['lesson-9-3'],
            estimatedMinutes: 5,
            difficulty: 4,
            sections: [
              {
                id: 'sec-10-1-1',
                type: 'word',
                title: 'সরল ও মাঝারি বাক্য ড্রিল',
                items: [
                  'আমি যাই।',
                  'পাখি গান গায়।',
                  'আমি আজ বাজারে যাই।',
                  'সততা মানুষের সবচেয়ে বড় গুণ।',
                  'শিক্ষা জাতির মেরুদণ্ড।',
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-10-1-2',
                type: 'mastery',
                title: 'সরল বাক্য মাস্টারি',
                items: [
                  'আমি যাই।',
                  'আমি আজ বাজারে যাই।',
                  'শিক্ষা জাতির মেরুদণ্ড।',
                  'সততা মানুষের সবচেয়ে বড় গুণ।',
                ],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-10-2',
            title: 'Sentence 3 & 4: দীর্ঘ ও জটিল যৌগিক বাক্য',
            subtitle: 'আমি আজ সকালে বাজারে গিয়েছিলাম এবং তাজা ফল এনেছি।',
            level: 10,
            moduleId: 'mod-10-1',
            moduleTitle: 'বাক্যের কাঠিন্য স্তর',
            description: 'যুক্তাক্ষর, বিরামচিহ্ন ও সংখ্যা সহযোগে দীর্ঘ ও পূর্ণাঙ্গ বাক্য।',
            skills: ['sentence-stage-3-4'],
            prerequisites: ['lesson-10-1'],
            estimatedMinutes: 6,
            difficulty: 5,
            sections: [
              {
                id: 'sec-10-2-1',
                type: 'word',
                title: 'দীর্ঘ ও জটিল বাক্য ড্রিল',
                items: [
                  'আমি আজ সকালে বাজারে গিয়েছিলাম এবং পরিবারের জন্য তাজা ফল এনেছি।',
                  'ডিজিটাল বাংলাদেশের অগ্রগতিতে তরুণ প্রজন্মের তথ্যপ্রযুক্তি দক্ষতা অনস্বীকার্য।',
                  'নিয়মিত ধৈর্য সহকারে টাইপিং অনুশীলন করলে গতি ও নির্ভুলতা দুটোই বহুগুণ বৃদ্ধি পায়।',
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-10-2-2',
                type: 'mastery',
                title: 'বাক্য ক্রমবিকাশ মাস্টারি',
                items: [
                  'আমি আজ সকালে বাজারে গিয়েছিলাম এবং পরিবারের জন্য তাজা ফল এনেছি।',
                  'ডিজিটাল বাংলাদেশের অগ্রগতিতে তরুণ প্রজন্মের তথ্যপ্রযুক্তি দক্ষতা অনস্বীকার্য।',
                  'নিয়মিত ধৈর্য সহকারে টাইপিং অনুশীলন করলে গতি ও নির্ভুলতা দুটোই বৃদ্ধি পায়।',
                ],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 11: বাস্তব জীবনের অনুচ্ছেদ ও সাহিত্য (LITERATURE & DRAFTS) ────
  {
    level: 11,
    title: 'বাস্তব জীবনের অনুচ্ছেদ ও সাহিত্য (Literature & Real-World)',
    tagline: 'সহজ পাঠ, রবীন্দ্রনাথ, নজরুল, মুক্তিযুদ্ধ ও অফিসিয়াল আবেদনপত্র',
    description: 'ধ্রুপদী সাহিত্য, ইতিহাস এবং বাস্তব পেশাগত ডকুমেন্টের একটানা টাইপিং স্ট্যামিনা।',
    badge: '📰',
    modules: [
      {
        id: 'mod-11-1',
        level: 11,
        title: 'সাহিত্য ও বাস্তব নথি',
        description: 'সহজ পাঠ, কবিতা, প্রবন্ধ ও অফিসিয়াল ড্রাফট',
        lessons: [
          {
            id: 'lesson-11-1',
            title: 'সহজ পাঠ (প্রথম ও দ্বিতীয় ভাগ)',
            subtitle: 'বনে থাকে বাঘ। গাছে থাকে পাখি। জলে থাকে মাছ।',
            level: 11,
            moduleId: 'mod-11-1',
            moduleTitle: 'সাহিত্য ও বাস্তব নথি',
            description: 'রবীন্দ্রনাথ ঠাকুরের সহজ পাঠের জনপ্রিয় অনুচ্ছেদ টাইপিং।',
            skills: ['sahaj-path'],
            prerequisites: ['lesson-10-2'],
            estimatedMinutes: 6,
            difficulty: 5,
            sections: [
              {
                id: 'sec-11-1-1',
                type: 'word',
                title: 'সহজ পাঠ ড্রিল',
                items: [
                  'বনে থাকে বাঘ। গাছে থাকে পাখি। জলে থাকে মাছ। ডালে আছে ফল। পাখি ফল খায়। পাখা মেলে ওড়ে। বাঘ আছে আম-বনে। গায়ে চাকা চাকা দাগ। পাখি বনে গান গায়। মাছ জলে খেলা করে।',
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-11-1-2',
                type: 'mastery',
                title: 'সহজ পাঠ মাস্টারি',
                items: [
                  'বনে থাকে বাঘ। গাছে থাকে পাখি। জলে থাকে মাছ। ডালে আছে ফল। পাখি ফল খায়। পাখা মেলে ওড়ে।',
                ],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-11-2',
            title: 'কবিতা ও ধ্রুপদী সাহিত্য (নির্ঝরের স্বপ্নভঙ্গ ও বিদ্রোহী)',
            subtitle: 'আজি এ প্রভাতে রবির কর / বল বীর - বল উন্নত মম শির',
            level: 11,
            moduleId: 'mod-11-1',
            moduleTitle: 'সাহিত্য ও বাস্তব নথি',
            description: 'ধ্রুপদী ছন্দে বাংলা কবিতার দ্রুত টাইপিং অনুশীলন।',
            skills: ['classic-literature'],
            prerequisites: ['lesson-11-1'],
            estimatedMinutes: 7,
            difficulty: 6,
            sections: [
              {
                id: 'sec-11-2-1',
                type: 'word',
                title: 'কবিতা ড্রিল',
                items: [
                  'আজি এ প্রভাতে রবির কর কেমনে পশিল প্রাণের \'পর, কেমনে পশিল গুহার আঁধারে প্রভাতপাখির গান! না জানি কেন রে এতদিন পরে জাগিয়া উঠিল প্রাণ।',
                  'বল বীর- বল উন্নত মম শির! শির নেহারি\' আমারি, নতশির ওই শিখর হিমাদ্রির! বল বীর- আমি চির-উন্নত শির!',
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-11-2-2',
                type: 'mastery',
                title: 'ধ্রুপদী সাহিত্য মাস্টারি',
                items: [
                  'বল বীর- বল উন্নত মম শির! শির নেহারি\' আমারি, নতশির ওই শিখর হিমাদ্রির! বল বীর- আমি চির-উন্নত শির!',
                ],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-11-3',
            title: 'অফিসিয়াল আবেদনপত্র ও দাপ্তরিক নথি',
            subtitle: 'বরাবর, মহাব্যবস্থাপক, বিষয়: ছুটির আবেদন',
            level: 11,
            moduleId: 'mod-11-1',
            moduleTitle: 'সাহিত্য ও বাস্তব নথি',
            description: 'পেশাগত জীবনের আসল আবেদনপত্র ও দাপ্তরিক ফরম্যাটের ড্রাফট।',
            skills: ['office-drafts'],
            prerequisites: ['lesson-11-2'],
            estimatedMinutes: 7,
            difficulty: 6,
            sections: [
              {
                id: 'sec-11-3-1',
                type: 'word',
                title: 'আবেদনপত্র ড্রিল',
                items: [
                  'বরাবর, মহাব্যবস্থাপক, বিষয়: ছুটির জন্য আবেদন। বিনীত নিবেদন এই যে, অসুস্থতার কারণে আমি আগামী তিন দিন উপস্থিত থাকতে পারছি না। অতএব প্রার্থনা, আমাকে ছুটি দানে বাধিত করবেন।',
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-11-3-2',
                type: 'mastery',
                title: 'অফিসিয়াল ডকুমেন্ট মাস্টারি',
                items: [
                  'গণপ্রজাতন্ত্রী বাংলাদেশ সরকারের ডিজিটাল রূপান্তরের অংশ হিসেবে সকল দাপ্তরিক কাজে বাংলা টাইপিংয়ের সঠিক প্রয়োগ নিশ্চিত করা অত্যাবশ্যকীয়।',
                ],
                requiredAccuracy: 96,
              },
            ],
          },
        ],
      },
    ],
  },

  // ── LEVEL 12: গতি প্রশিক্ষণ ও চূড়ান্ত পরীক্ষা (SPEED & STRICT EXAM) ─────
  {
    level: 12,
    title: 'গতি প্রশিক্ষণ ও সরকারি পরীক্ষা সিমুলেশন (Speed & Certification Exam)',
    tagline: '৪০+ WPM স্প্রিন্ট এবং সরকারি নিয়োগ পরীক্ষার হুবহু পরিবেশ',
    description: 'স্ট্রিক্ট টাইমার, নো পজ ও অফিসিয়াল ভেরিফায়েড সনদপত্র অর্জনের চূড়ান্ত পরীক্ষা।',
    badge: '🎓',
    modules: [
      {
        id: 'mod-12-1',
        level: 12,
        title: 'স্পিড স্প্রিন্ট ও চূড়ান্ত এক্সাম',
        description: 'উচ্চ গতির অনুশীলন ও ৫ মিনিটের ভেরিফায়েড টেস্ট',
        lessons: [
          {
            id: 'lesson-12-1',
            title: '৪০+ WPM হাই-স্পিড স্প্রিন্ট',
            subtitle: 'উচ্চ গতির জন্য ফাস্ট প্যাসেজ ড্রিল',
            level: 12,
            moduleId: 'mod-12-1',
            moduleTitle: 'স্পিড স্প্রিন্ট ও চূড়ান্ত এক্সাম',
            description: 'কম সময়ে সর্বোচ্চ গতি ও একটানা নির্ভুলতা ধরে রাখার চ্যালেঞ্জ।',
            skills: ['speed-sprint'],
            prerequisites: ['lesson-11-3'],
            estimatedMinutes: 5,
            difficulty: 8,
            sections: [
              {
                id: 'sec-12-1-1',
                type: 'word',
                title: 'স্পিড স্প্রিন্ট',
                items: [
                  'বাংলা আমাদের অহংকার এবং মাতৃভাষা। দ্রুত নির্ভুল টাইপিং দক্ষতা আপনার সময় বাঁচায় ও কর্মক্ষমতা বহুগুণ বাড়িয়ে দেয়। নিয়মিত টাইপিং অনুশীলনের মাধ্যমে আমরা প্রত্যেকেই দক্ষ হয়ে উঠতে পারি।',
                ],
                requiredAccuracy: 95,
              },
              {
                id: 'sec-12-1-2',
                type: 'mastery',
                title: 'স্পিড টেস্ট মাস্টারি',
                items: [
                  'সততা, নিষ্ঠা ও নিয়মিত অনুশীলনের মাধ্যমেই যেকোনো কঠিন দক্ষতায় পারদর্শী হওয়া সম্ভব। টাইপিংয়ে আত্মবিশ্বাসই সাফল্যের মূল চাবিকাঠি।',
                ],
                requiredAccuracy: 96,
              },
            ],
          },
          {
            id: 'lesson-12-2',
            title: 'চূড়ান্ত সরকারি নিয়োগ পরীক্ষা (Final Certification Exam)',
            subtitle: '৫ মিনিটের স্ট্রিক্ট নিয়োগ পরীক্ষা সিমুলেশন',
            level: 12,
            moduleId: 'mod-12-1',
            moduleTitle: 'স্পিড স্প্রিন্ট ও চূড়ান্ত এক্সাম',
            description: 'আসল পরীক্ষার প্যাসেজ টাইপ করে অফিসিয়াল ভেরিফায়েড সার্টিফিকেট অর্জন করুন।',
            skills: ['final-exam-simulation'],
            prerequisites: ['lesson-12-1'],
            estimatedMinutes: 5,
            difficulty: 9,
            sections: [
              {
                id: 'sec-12-2-1',
                type: 'mastery',
                title: 'চূড়ান্ত নিয়োগ পরীক্ষা',
                instruction: 'কোনো বিরতি ছাড়াই পুরো প্যাসেজটি টাইপ করুন। সর্বনিম্ন ৯৫% নির্ভুলতা ও ৩০ WPM গতি প্রয়োজন।',
                items: [
                  'ডিজিটাল বাংলাদেশ বিনির্মাণে বাংলা ভাষার সঠিক ব্যবহার ও ডিজিটাইজেশন একটি তাৎপর্যপূর্ণ পদক্ষেপ। বর্তমান যুগে প্রতিটি সরকারি ও বেসরকারি প্রতিষ্ঠানে দক্ষ বাংলা টাইপিস্টদের চাহিদা উত্তরোত্তর বৃদ্ধি পাচ্ছে। যারা নির্ভুল ও দ্রুত গতিতে টাইপ করতে পারেন, তারা দাপ্তরিক কাজে দ্রুত ফলাফল অর্জন করেন। নিয়মিত অনুশীলন, ধৈর্য এবং সঠিক কীবোর্ড লেআউট অনুসরণের মাধ্যমে প্রত্যেকেই বাংলা টাইপিংয়ে অসাধারণ দক্ষতা অর্জন করতে পারে।',
                ],
                requiredAccuracy: 95,
              },
            ],
          },
        ],
      },
    ],
  },
];

/** Helper: Find lesson by ID across all levels */
export function getCurriculumLessonById(lessonId: string): CurriculumLesson | undefined {
  for (const lvl of CURRICULUM_LEVELS) {
    for (const mod of lvl.modules) {
      for (const les of mod.lessons) {
        if (les.id === lessonId) return les;
      }
    }
  }
  return undefined;
}

/** Helper: Get all lessons in linear order */
export function getAllCurriculumLessons(): CurriculumLesson[] {
  const all: CurriculumLesson[] = [];
  for (const lvl of CURRICULUM_LEVELS) {
    for (const mod of lvl.modules) {
      for (const les of mod.lessons) {
        all.push(les);
      }
    }
  }
  return all;
}
